	.align 2
DirectSoundWaveData_Tone1:: @ 8456330
	.incbin "sound/direct_sound_samples/synth/tone1.bin"

	.align 2
DirectSoundWaveData_SC88_Organ2:: @ 84569D4
	.incbin "sound/direct_sound_samples/synth/sc88_18_organ_2.bin"

	.align 2
DirectSoundWaveData_SC88_FretlessBass:: @ 84571CC
	.incbin "sound/direct_sound_samples/synth/sc88_36_fretless_bass.bin"

	.align 2
DirectSoundWaveData_SC88_FingerSlap:: @ 8457D98
	.incbin "sound/direct_sound_samples/synth/sc88_34_finger_slap.bin"

	.align 2
DirectSoundWaveData_SC88_SynthBass1:: @ 8458CD0
	.incbin "sound/direct_sound_samples/synth/sc88_39_synth_bass_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitTimbale2:: @ 8459944
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_timbale_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitBassDrum:: @ 845AE14
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_bass_drum.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare1:: @ 845B2B4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitHandClap:: @ 845B9A8
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_hand_clap.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare2:: @ 845C238
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitHiMidTom:: @ 845CAB0
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_hi_mid_tom.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitClosedHiHat:: @ 845DAF0
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_closed_hi_hat.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitOpenHiHat:: @ 845DF04
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_open_hi_hat.bin"

	.align 2
DirectSoundWaveData_HiHatRattle:: @ 845ED34
	.incbin "sound/direct_sound_samples/synth/hi_hat_rattle.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCabasa:: @ 845FCC8
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_cabasa.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCrashCymbal2:: @ 846057C
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_crash_cymbal_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCrashCymbal1:: @ 8460E60
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_crash_cymbal_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitMuteHiConga:: @ 8461D8C
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_mute_hi_conga.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitLowConga:: @ 84622A4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_low_conga.bin"

	.align 2
DirectSoundWaveData_SC88_SteelStringGuitar:: @ 846286C
	.incbin "sound/direct_sound_samples/synth/sc88_26_steel_string_guitar.bin"

	.align 2
DirectSoundWaveData_SC88_Piano3:: @ 84637CC
	.incbin "sound/direct_sound_samples/synth/sc88_3_piano_3.bin"

	.align 2
DirectSoundWaveData_SC88_Piano2:: @ 8464E2C
	.incbin "sound/direct_sound_samples/synth/sc88_2_piano_2.bin"

	.align 2
DirectSoundWaveData_SC88_UnisonSlap:: @ 8466388
	.incbin "sound/direct_sound_samples/synth/sc88_37_unison_slap.bin"

	.align 2
DirectSoundWaveData_SC88_Strings:: @ 8466F14
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings.bin"

	.align 2
DirectSoundWaveData_SC88_StringsPlusFlute:: @ 846A4B8
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings_plus_flute.bin"

	.align 2
DirectSoundWaveData_SC88_StringsPlusHorn:: @ 846C7D4
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings_plus_horn.bin"

	.align 2
DirectSoundWaveData_SC88_Trumpet:: @ 846FEA0
	.incbin "sound/direct_sound_samples/synth/sc88_57_trumpet.bin"

	.align 2
DirectSoundWaveData_SC88_Trombone:: @ 84711F0
	.incbin "sound/direct_sound_samples/synth/sc88_58_trombone.bin"

	.align 2
DirectSoundWaveData_SC88_Tuba:: @ 8472700
	.incbin "sound/direct_sound_samples/synth/sc88_59_tuba.bin"

	.align 2
DirectSoundWaveData_SC88_CupMutedTrumpet:: @ 8473B20
	.incbin "sound/direct_sound_samples/synth/sc88_60_cup_muted_trumpet.bin"

	.align 2
DirectSoundWaveData_SC88_MutedTrumpet3:: @ 8474BBC
	.incbin "sound/direct_sound_samples/synth/sc88_60_muted_trumpet_3.bin"

	.align 2
DirectSoundWaveData_SC88_FrenchHorns:: @ 8475C18
	.incbin "sound/direct_sound_samples/synth/sc88_61_french_horns.bin"

	.align 2
DirectSoundWaveData_SC88_WideFrenchHorns:: @ 847CBAC
	.incbin "sound/direct_sound_samples/synth/sc88_61_wide_french_horns.bin"

	.align 2
DirectSoundWaveData_SC88_NylonStringGuitar:: @ 8481130
	.incbin "sound/direct_sound_samples/synth/sc88_25_nylon_string_guitar.bin"

	.align 2
DirectSoundWaveData_SC88_Flute:: @ 84830A0
	.incbin "sound/direct_sound_samples/synth/sc88_74_flute.bin"

	.align 2
DirectSoundWaveData_SC88_FingeredBass:: @ 8483804
	.incbin "sound/direct_sound_samples/synth/sc88_34_fingered_bass.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitTimbale1:: @ 8485454
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_timbale_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare4:: @ 8486924
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_4.bin"

	.align 2
DirectSoundWaveData_SC88_SquareWave:: @ 8487330
	.incbin "sound/direct_sound_samples/synth/sc88_81_square_wave.bin"

	.align 2
DirectSoundWaveData_Ring:: @ 8488F44
	.incbin "sound/direct_sound_samples/synth/ring.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare3:: @ 848A8A4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_3.bin"

	.align 2
DirectSoundWaveData_SC88_PizzicatoStrings:: @ 848BD68
	.incbin "sound/direct_sound_samples/synth/sc88_46_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_MachineSound2:: @ 848C4A4
	.incbin "sound/direct_sound_samples/synth/machine_sound2.bin"

	.align 2
DirectSoundWaveData_MachineSound1:: @ 848E094
	.incbin "sound/direct_sound_samples/synth/machine_sound1.bin"

	.align 2
DirectSoundWaveData_SC88_Applause2:: @ 848F448
	.incbin "sound/direct_sound_samples/synth/sc88_127_applause_2.bin"

	.align 2
DirectSoundWaveData_Noise3:: @ 8491ACC
	.incbin "sound/direct_sound_samples/synth/noise3.bin"

	.align 2
DirectSoundWaveData_SC88_Bubble:: @ 8492D10
	.incbin "sound/direct_sound_samples/synth/sc88_123_bubble.bin"

	.align 2
DirectSoundWaveData_SC88_CarCrash:: @ 8493D20
	.incbin "sound/direct_sound_samples/synth/sc88_126_car_crash.bin"

	.align 2
DirectSoundWaveData_SC88_PinkNoise:: @ 8495028
	.incbin "sound/direct_sound_samples/synth/sc88_123_pink_noise.bin"

	.align 2
DirectSoundWaveData_SC88_WaspySynth:: @ 8497134
	.incbin "sound/direct_sound_samples/synth/sc88_82_waspy_synth.bin"

	.align 2
DirectSoundWaveData_SC88_WhiteNoise:: @ 8499110
	.incbin "sound/direct_sound_samples/synth/sc88_123_white_noise.bin"

	.align 2
DirectSoundWaveData_SC88_DrumkitGuiro:: @ 849B320
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_guiro.bin"

	.align 2
DirectSoundWaveData_SC88_TubularBell:: @ 849BAEC
	.incbin "sound/direct_sound_samples/synth/sc88_15_tubular_bell.bin"

	.align 2
DirectSoundWaveData_Noise1:: @ 849D45C
	.incbin "sound/direct_sound_samples/synth/noise1.bin"

	.align 2
DirectSoundWaveData_SC88_JPSuperSaw:: @ 849F40C
	.incbin "sound/direct_sound_samples/synth/sc88_82_jp_super_saw.bin"

	.align 2
DirectSoundWaveData_SC88_Piano1:: @ 84A26EC
	.incbin "sound/direct_sound_samples/synth/sc88_1_piano_1.bin"

	.align 2
DirectSoundWaveData_SC88_Marimba:: @ 84A311C
	.incbin "sound/direct_sound_samples/synth/sc88_13_marimba.bin"

	.align 2
DirectSoundWaveData_Noise2:: @ 84A3B50
	.incbin "sound/direct_sound_samples/synth/noise2.bin"

	.align 2
DirectSoundWaveData_SC88_HorseGallop:: @ 84A5690
	.incbin "sound/direct_sound_samples/synth/sc88_124_horse_gallop.bin"

	.align 2
DirectSoundWaveData_SC88_AccordianFr:: @ 84A5F58
	.incbin "sound/direct_sound_samples/synth/sc88_22_accordion_fr.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel1:: @ 84A7328
	.incbin "sound/direct_sound_samples/phonemes/vowel_1.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel2:: @ 84A7F38
	.incbin "sound/direct_sound_samples/phonemes/vowel_2.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel3:: @ 84A8AC8
	.incbin "sound/direct_sound_samples/phonemes/vowel_3.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel4:: @ 84A9564
	.incbin "sound/direct_sound_samples/phonemes/vowel_4.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel5:: @ 84A9EAC
	.incbin "sound/direct_sound_samples/phonemes/vowel_5.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel6:: @ 84AA8F4
	.incbin "sound/direct_sound_samples/phonemes/vowel_6.bin"

	.align 2
Cry_Bulbasaur:: @ 84AB57C
	.incbin "sound/direct_sound_samples/cries/cry_bulbasaur.bin"

	.align 2
Cry_Ivysaur:: @ 84AC608
	.incbin "sound/direct_sound_samples/cries/cry_ivysaur.bin"

	.align 2
Cry_Venusaur:: @ 84AD698
	.incbin "sound/direct_sound_samples/cries/cry_venusaur.bin"

	.align 2
Cry_Charmander:: @ 84AE9F0
	.incbin "sound/direct_sound_samples/cries/cry_charmander.bin"

	.align 2
Cry_Charmeleon:: @ 84AF860
	.incbin "sound/direct_sound_samples/cries/cry_charmeleon.bin"

	.align 2
Cry_Charizard:: @ 84B06E0
	.incbin "sound/direct_sound_samples/cries/cry_charizard.bin"

	.align 2
Cry_Squirtle:: @ 84B1A28
	.incbin "sound/direct_sound_samples/cries/cry_squirtle.bin"

	.align 2
Cry_Wartortle:: @ 84B289C
	.incbin "sound/direct_sound_samples/cries/cry_wartortle.bin"

	.align 2
Cry_Blastoise:: @ 84B39DC
	.incbin "sound/direct_sound_samples/cries/cry_blastoise.bin"

	.align 2
Cry_Caterpie:: @ 84B4D24
	.incbin "sound/direct_sound_samples/cries/cry_caterpie.bin"

	.align 2
Cry_Metapod:: @ 84B557C
	.incbin "sound/direct_sound_samples/cries/cry_metapod.bin"

	.align 2
Cry_Butterfree:: @ 84B6CCC
	.incbin "sound/direct_sound_samples/cries/cry_butterfree.bin"

	.align 2
Cry_Weedle:: @ 84B76D4
	.incbin "sound/direct_sound_samples/cries/cry_weedle.bin"

	.align 2
Cry_Kakuna:: @ 84B8718
	.incbin "sound/direct_sound_samples/cries/cry_kakuna.bin"

	.align 2
Cry_Beedrill:: @ 84B9954
	.incbin "sound/direct_sound_samples/cries/cry_beedrill.bin"

	.align 2
Cry_Pidgey:: @ 84BACB0
	.incbin "sound/direct_sound_samples/cries/cry_pidgey.bin"

	.align 2
Cry_Pidgeotto:: @ 84BB098
	.incbin "sound/direct_sound_samples/cries/cry_pidgeotto.bin"

	.align 2
Cry_Pidgeot:: @ 84BBFA0
	.incbin "sound/direct_sound_samples/cries/cry_pidgeot.bin"

	.align 2
Cry_Rattata:: @ 84BD0D4
	.incbin "sound/direct_sound_samples/cries/cry_rattata.bin"

	.align 2
Cry_Raticate:: @ 84BD8B4
	.incbin "sound/direct_sound_samples/cries/cry_raticate.bin"

	.align 2
Cry_Spearow:: @ 84BE238
	.incbin "sound/direct_sound_samples/cries/cry_spearow.bin"

	.align 2
Cry_Fearow:: @ 84BF3DC
	.incbin "sound/direct_sound_samples/cries/cry_fearow.bin"

	.align 2
Cry_Ekans:: @ 84C0518
	.incbin "sound/direct_sound_samples/cries/cry_ekans.bin"

	.align 2
Cry_Arbok:: @ 84C1864
	.incbin "sound/direct_sound_samples/cries/cry_arbok.bin"

	.align 2
Cry_Pikachu:: @ 84C2BBC
	.incbin "sound/direct_sound_samples/cries/cry_pikachu.bin"

	.align 2
Cry_Raichu:: @ 84C3C64
	.incbin "sound/direct_sound_samples/cries/cry_raichu.bin"

	.align 2
Cry_Sandshrew:: @ 84C5424
	.incbin "sound/direct_sound_samples/cries/cry_sandshrew.bin"

	.align 2
Cry_Sandslash:: @ 84C5D78
	.incbin "sound/direct_sound_samples/cries/cry_sandslash.bin"

	.align 2
Cry_NidoranF:: @ 84C6B08
	.incbin "sound/direct_sound_samples/cries/cry_nidoran_f.bin"

	.align 2
Cry_Nidorina:: @ 84C74B8
	.incbin "sound/direct_sound_samples/cries/cry_nidorina.bin"

	.align 2
Cry_Nidoqueen:: @ 84C8180
	.incbin "sound/direct_sound_samples/cries/cry_nidoqueen.bin"

	.align 2
Cry_NidoranM:: @ 84C9260
	.incbin "sound/direct_sound_samples/cries/cry_nidoran_m.bin"

	.align 2
Cry_Nidorino:: @ 84C9CC8
	.incbin "sound/direct_sound_samples/cries/cry_nidorino.bin"

	.align 2
Cry_Nidoking:: @ 84CA8DC
	.incbin "sound/direct_sound_samples/cries/cry_nidoking.bin"

	.align 2
Cry_Clefairy:: @ 84CC148
	.incbin "sound/direct_sound_samples/cries/cry_clefairy.bin"

	.align 2
Cry_Clefable:: @ 84CC9B8
	.incbin "sound/direct_sound_samples/cries/cry_clefable.bin"

	.align 2
Cry_Vulpix:: @ 84CD448
	.incbin "sound/direct_sound_samples/cries/cry_vulpix.bin"

	.align 2
Cry_Ninetales:: @ 84CEC18
	.incbin "sound/direct_sound_samples/cries/cry_ninetales.bin"

	.align 2
Cry_Jigglypuff:: @ 84D0484
	.incbin "sound/direct_sound_samples/cries/cry_jigglypuff.bin"

	.align 2
Cry_Wigglytuff:: @ 84D09E8
	.incbin "sound/direct_sound_samples/cries/cry_wigglytuff.bin"

	.align 2
Cry_Zubat:: @ 84D10B0
	.incbin "sound/direct_sound_samples/cries/cry_zubat.bin"

	.align 2
Cry_Golbat:: @ 84D241C
	.incbin "sound/direct_sound_samples/cries/cry_golbat.bin"

	.align 2
Cry_Oddish:: @ 84D3780
	.incbin "sound/direct_sound_samples/cries/cry_oddish.bin"

	.align 2
Cry_Gloom:: @ 84D461C
	.incbin "sound/direct_sound_samples/cries/cry_gloom.bin"

	.align 2
Cry_Vileplume:: @ 84D5298
	.incbin "sound/direct_sound_samples/cries/cry_vileplume.bin"

	.align 2
Cry_Paras:: @ 84D6C34
	.incbin "sound/direct_sound_samples/cries/cry_paras.bin"

	.align 2
Cry_Parasect:: @ 84D8828
	.incbin "sound/direct_sound_samples/cries/cry_parasect.bin"

	.align 2
Cry_Venonat:: @ 84DA690
	.incbin "sound/direct_sound_samples/cries/cry_venonat.bin"

	.align 2
Cry_Venomoth:: @ 84DB610
	.incbin "sound/direct_sound_samples/cries/cry_venomoth.bin"

	.align 2
Cry_Diglett:: @ 84DC614
	.incbin "sound/direct_sound_samples/cries/cry_diglett.bin"

	.align 2
Cry_Dugtrio:: @ 84DD984
	.incbin "sound/direct_sound_samples/cries/cry_dugtrio.bin"

	.align 2
Cry_Meowth:: @ 84DECF0
	.incbin "sound/direct_sound_samples/cries/cry_meowth.bin"

	.align 2
Cry_Persian:: @ 84DF680
	.incbin "sound/direct_sound_samples/cries/cry_persian.bin"

	.align 2
Cry_Psyduck:: @ 84E095C
	.incbin "sound/direct_sound_samples/cries/cry_psyduck.bin"

	.align 2
Cry_Golduck:: @ 84E1684
	.incbin "sound/direct_sound_samples/cries/cry_golduck.bin"

	.align 2
Cry_Mankey:: @ 84E21CC
	.incbin "sound/direct_sound_samples/cries/cry_mankey.bin"

	.align 2
Cry_Primeape:: @ 84E322C
	.incbin "sound/direct_sound_samples/cries/cry_primeape.bin"

	.align 2
Cry_Growlithe:: @ 84E425C
	.incbin "sound/direct_sound_samples/cries/cry_growlithe.bin"

	.align 2
Cry_Arcanine:: @ 84E4FC0
	.incbin "sound/direct_sound_samples/cries/cry_arcanine.bin"

	.align 2
Cry_Poliwag:: @ 84E60FC
	.incbin "sound/direct_sound_samples/cries/cry_poliwag.bin"

	.align 2
Cry_Poliwhirl:: @ 84E6C18
	.incbin "sound/direct_sound_samples/cries/cry_poliwhirl.bin"

	.align 2
Cry_Poliwrath:: @ 84E72C0
	.incbin "sound/direct_sound_samples/cries/cry_poliwrath.bin"

	.align 2
Cry_Abra:: @ 84E7DE4
	.incbin "sound/direct_sound_samples/cries/cry_abra.bin"

	.align 2
Cry_Kadabra:: @ 84E9548
	.incbin "sound/direct_sound_samples/cries/cry_kadabra.bin"

	.align 2
Cry_Alakazam:: @ 84EB030
	.incbin "sound/direct_sound_samples/cries/cry_alakazam.bin"

	.align 2
Cry_Machop:: @ 84ECFCC
	.incbin "sound/direct_sound_samples/cries/cry_machop.bin"

	.align 2
Cry_Machoke:: @ 84EDD30
	.incbin "sound/direct_sound_samples/cries/cry_machoke.bin"

	.align 2
Cry_Machamp:: @ 84EEAC0
	.incbin "sound/direct_sound_samples/cries/cry_machamp.bin"

	.align 2
Cry_Bellsprout:: @ 84EFB48
	.incbin "sound/direct_sound_samples/cries/cry_bellsprout.bin"

	.align 2
Cry_Weepinbell:: @ 84F02D4
	.incbin "sound/direct_sound_samples/cries/cry_weepinbell.bin"

	.align 2
Cry_Victreebel:: @ 84F1174
	.incbin "sound/direct_sound_samples/cries/cry_victreebel.bin"

	.align 2
Cry_Tentacool:: @ 84F24C0
	.incbin "sound/direct_sound_samples/cries/cry_tentacool.bin"

	.align 2
Cry_Tentacruel:: @ 84F34B0
	.incbin "sound/direct_sound_samples/cries/cry_tentacruel.bin"

	.align 2
Cry_Geodude:: @ 84F4BAC
	.incbin "sound/direct_sound_samples/cries/cry_geodude.bin"

	.align 2
Cry_Graveler:: @ 84F6360
	.incbin "sound/direct_sound_samples/cries/cry_graveler.bin"

	.align 2
Cry_Golem:: @ 84F7F48
	.incbin "sound/direct_sound_samples/cries/cry_golem.bin"

	.align 2
Cry_Ponyta:: @ 84F8D74
	.incbin "sound/direct_sound_samples/cries/cry_ponyta.bin"

	.align 2
Cry_Rapidash:: @ 84F9C84
	.incbin "sound/direct_sound_samples/cries/cry_rapidash.bin"

	.align 2
Cry_Slowpoke:: @ 84FAF24
	.incbin "sound/direct_sound_samples/cries/cry_slowpoke.bin"

	.align 2
Cry_Slowbro:: @ 84FB68C
	.incbin "sound/direct_sound_samples/cries/cry_slowbro.bin"

	.align 2
Cry_Magnemite:: @ 84FC3FC
	.incbin "sound/direct_sound_samples/cries/cry_magnemite.bin"

	.align 2
Cry_Magneton:: @ 84FD740
	.incbin "sound/direct_sound_samples/cries/cry_magneton.bin"

	.align 2
Cry_Farfetchd:: @ 84FEF28
	.incbin "sound/direct_sound_samples/cries/cry_farfetchd.bin"

	.align 2
Cry_Doduo:: @ 84FF6A4
	.incbin "sound/direct_sound_samples/cries/cry_doduo.bin"

	.align 2
Cry_Dodrio:: @ 85009E8
	.incbin "sound/direct_sound_samples/cries/cry_dodrio.bin"

	.align 2
Cry_Seel:: @ 8501D60
	.incbin "sound/direct_sound_samples/cries/cry_seel.bin"

	.align 2
Cry_Dewgong:: @ 8502F50
	.incbin "sound/direct_sound_samples/cries/cry_dewgong.bin"

	.align 2
Cry_Grimer:: @ 8504474
	.incbin "sound/direct_sound_samples/cries/cry_grimer.bin"

	.align 2
Cry_Muk:: @ 8504EFC
	.incbin "sound/direct_sound_samples/cries/cry_muk.bin"

	.align 2
Cry_Shellder:: @ 8505DBC
	.incbin "sound/direct_sound_samples/cries/cry_shellder.bin"

	.align 2
Cry_Cloyster:: @ 8506D30
	.incbin "sound/direct_sound_samples/cries/cry_cloyster.bin"

	.align 2
Cry_Gastly:: @ 85081F4
	.incbin "sound/direct_sound_samples/cries/cry_gastly.bin"

	.align 2
Cry_Haunter:: @ 8509944
	.incbin "sound/direct_sound_samples/cries/cry_haunter.bin"

	.align 2
Cry_Gengar:: @ 850B0C4
	.incbin "sound/direct_sound_samples/cries/cry_gengar.bin"

	.align 2
Cry_Onix:: @ 850BF84
	.incbin "sound/direct_sound_samples/cries/cry_onix.bin"

	.align 2
Cry_Drowzee:: @ 850D848
	.incbin "sound/direct_sound_samples/cries/cry_drowzee.bin"

	.align 2
Cry_Hypno:: @ 850F560
	.incbin "sound/direct_sound_samples/cries/cry_hypno.bin"

	.align 2
Cry_Krabby:: @ 8511264
	.incbin "sound/direct_sound_samples/cries/cry_krabby.bin"

	.align 2
Cry_Kingler:: @ 8512AB0
	.incbin "sound/direct_sound_samples/cries/cry_kingler.bin"

	.align 2
Cry_Voltorb:: @ 8514308
	.incbin "sound/direct_sound_samples/cries/cry_voltorb.bin"

	.align 2
Cry_Electrode:: @ 8515BCC
	.incbin "sound/direct_sound_samples/cries/cry_electrode.bin"

	.align 2
Cry_Exeggcute:: @ 8517504
	.incbin "sound/direct_sound_samples/cries/cry_exeggcute.bin"

	.align 2
Cry_Exeggutor:: @ 85187E4
	.incbin "sound/direct_sound_samples/cries/cry_exeggutor.bin"

	.align 2
Cry_Cubone:: @ 851A7C8
	.incbin "sound/direct_sound_samples/cries/cry_cubone.bin"

	.align 2
Cry_Marowak:: @ 851B6E8
	.incbin "sound/direct_sound_samples/cries/cry_marowak.bin"

	.align 2
Cry_Hitmonlee:: @ 851C558
	.incbin "sound/direct_sound_samples/cries/cry_hitmonlee.bin"

	.align 2
Cry_Hitmonchan:: @ 851D804
	.incbin "sound/direct_sound_samples/cries/cry_hitmonchan.bin"

	.align 2
Cry_Lickitung:: @ 851E9DC
	.incbin "sound/direct_sound_samples/cries/cry_lickitung.bin"

	.align 2
Cry_Koffing:: @ 851F904
	.incbin "sound/direct_sound_samples/cries/cry_koffing.bin"

	.align 2
Cry_Weezing:: @ 8520D60
	.incbin "sound/direct_sound_samples/cries/cry_weezing.bin"

	.align 2
Cry_Rhyhorn:: @ 852230C
	.incbin "sound/direct_sound_samples/cries/cry_rhyhorn.bin"

	.align 2
Cry_Rhydon:: @ 8523678
	.incbin "sound/direct_sound_samples/cries/cry_rhydon.bin"

	.align 2
Cry_Chansey:: @ 8524AE4
	.incbin "sound/direct_sound_samples/cries/cry_chansey.bin"

	.align 2
Cry_Tangela:: @ 85259B0
	.incbin "sound/direct_sound_samples/cries/cry_tangela.bin"

	.align 2
Cry_Kangaskhan:: @ 85268CC
	.incbin "sound/direct_sound_samples/cries/cry_kangaskhan.bin"

	.align 2
Cry_Horsea:: @ 8527B80
	.incbin "sound/direct_sound_samples/cries/cry_horsea.bin"

	.align 2
Cry_Seadra:: @ 85284FC
	.incbin "sound/direct_sound_samples/cries/cry_seadra.bin"

	.align 2
Cry_Goldeen:: @ 8528D68
	.incbin "sound/direct_sound_samples/cries/cry_goldeen.bin"

	.align 2
Cry_Seaking:: @ 8529740
	.incbin "sound/direct_sound_samples/cries/cry_seaking.bin"

	.align 2
Cry_Staryu:: @ 852AA98
	.incbin "sound/direct_sound_samples/cries/cry_staryu.bin"

	.align 2
Cry_Starmie:: @ 852BE80
	.incbin "sound/direct_sound_samples/cries/cry_starmie.bin"

	.align 2
Cry_MrMime:: @ 852D35C
	.incbin "sound/direct_sound_samples/cries/cry_mr_mime.bin"

	.align 2
Cry_Scyther:: @ 852E64C
	.incbin "sound/direct_sound_samples/cries/cry_scyther.bin"

	.align 2
Cry_Jynx:: @ 852F3A8
	.incbin "sound/direct_sound_samples/cries/cry_jynx.bin"

	.align 2
Cry_Electabuzz:: @ 853231C
	.incbin "sound/direct_sound_samples/cries/cry_electabuzz.bin"

	.align 2
Cry_Magmar:: @ 8534200
	.incbin "sound/direct_sound_samples/cries/cry_magmar.bin"

	.align 2
Cry_Pinsir:: @ 853517C
	.incbin "sound/direct_sound_samples/cries/cry_pinsir.bin"

	.align 2
Cry_Tauros:: @ 8535DD8
	.incbin "sound/direct_sound_samples/cries/cry_tauros.bin"

	.align 2
Cry_Magikarp:: @ 853702C
	.incbin "sound/direct_sound_samples/cries/cry_magikarp.bin"

	.align 2
Cry_Gyarados:: @ 8538334
	.incbin "sound/direct_sound_samples/cries/cry_gyarados.bin"

	.align 2
Cry_Lapras:: @ 8539768
	.incbin "sound/direct_sound_samples/cries/cry_lapras.bin"

	.align 2
Cry_Ditto:: @ 853A63C
	.incbin "sound/direct_sound_samples/cries/cry_ditto.bin"

	.align 2
Cry_Eevee:: @ 853B158
	.incbin "sound/direct_sound_samples/cries/cry_eevee.bin"

	.align 2
Cry_Vaporeon:: @ 853BF90
	.incbin "sound/direct_sound_samples/cries/cry_vaporeon.bin"

	.align 2
Cry_Jolteon:: @ 853D5A8
	.incbin "sound/direct_sound_samples/cries/cry_jolteon.bin"

	.align 2
Cry_Flareon:: @ 853E57C
	.incbin "sound/direct_sound_samples/cries/cry_flareon.bin"

	.align 2
Cry_Porygon:: @ 853F500
	.incbin "sound/direct_sound_samples/cries/cry_porygon.bin"

	.align 2
Cry_Omanyte:: @ 854090C
	.incbin "sound/direct_sound_samples/cries/cry_omanyte.bin"

	.align 2
Cry_Omastar:: @ 8541664
	.incbin "sound/direct_sound_samples/cries/cry_omastar.bin"

	.align 2
Cry_Kabuto:: @ 85423B8
	.incbin "sound/direct_sound_samples/cries/cry_kabuto.bin"

	.align 2
Cry_Kabutops:: @ 854300C
	.incbin "sound/direct_sound_samples/cries/cry_kabutops.bin"

	.align 2
Cry_Aerodactyl:: @ 8543DC8
	.incbin "sound/direct_sound_samples/cries/cry_aerodactyl.bin"

	.align 2
Cry_Snorlax:: @ 8545624
	.incbin "sound/direct_sound_samples/cries/cry_snorlax.bin"

	.align 2
Cry_Articuno:: @ 8545B60
	.incbin "sound/direct_sound_samples/cries/cry_articuno.bin"

	.align 2
Cry_Zapdos:: @ 8547308
	.incbin "sound/direct_sound_samples/cries/cry_zapdos.bin"

	.align 2
Cry_Moltres:: @ 8548280
	.incbin "sound/direct_sound_samples/cries/cry_moltres.bin"

	.align 2
Cry_Dratini:: @ 8549A2C
	.incbin "sound/direct_sound_samples/cries/cry_dratini.bin"

	.align 2
Cry_Dragonair:: @ 854A5C8
	.incbin "sound/direct_sound_samples/cries/cry_dragonair.bin"

	.align 2
Cry_Dragonite:: @ 854B670
	.incbin "sound/direct_sound_samples/cries/cry_dragonite.bin"

	.align 2
Cry_Mewtwo:: @ 854C97C
	.incbin "sound/direct_sound_samples/cries/cry_mewtwo.bin"

	.align 2
Cry_Mew:: @ 854E7E4
	.incbin "sound/direct_sound_samples/cries/cry_mew.bin"

	.align 2
Cry_Chikorita:: @ 855064C
	.incbin "sound/direct_sound_samples/cries/cry_chikorita.bin"

	.align 2
Cry_Bayleef:: @ 8550B8C
	.incbin "sound/direct_sound_samples/cries/cry_bayleef.bin"

	.align 2
Cry_Meganium:: @ 8551458
	.incbin "sound/direct_sound_samples/cries/cry_meganium.bin"

	.align 2
Cry_Cyndaquil:: @ 8552490
	.incbin "sound/direct_sound_samples/cries/cry_cyndaquil.bin"

	.align 2
Cry_Quilava:: @ 8552B94
	.incbin "sound/direct_sound_samples/cries/cry_quilava.bin"

	.align 2
Cry_Typhlosion:: @ 855377C
	.incbin "sound/direct_sound_samples/cries/cry_typhlosion.bin"

	.align 2
Cry_Totodile:: @ 8555D8C
	.incbin "sound/direct_sound_samples/cries/cry_totodile.bin"

	.align 2
Cry_Croconaw:: @ 8556FE4
	.incbin "sound/direct_sound_samples/cries/cry_croconaw.bin"

	.align 2
Cry_Feraligatr:: @ 8558420
	.incbin "sound/direct_sound_samples/cries/cry_feraligatr.bin"

	.align 2
Cry_Sentret:: @ 8559DA4
	.incbin "sound/direct_sound_samples/cries/cry_sentret.bin"

	.align 2
Cry_Furret:: @ 855A1CC
	.incbin "sound/direct_sound_samples/cries/cry_furret.bin"

	.align 2
Cry_Hoothoot:: @ 855A814
	.incbin "sound/direct_sound_samples/cries/cry_hoothoot.bin"

	.align 2
Cry_Noctowl:: @ 855B2F8
	.incbin "sound/direct_sound_samples/cries/cry_noctowl.bin"

	.align 2
Cry_Ledyba:: @ 855C828
	.incbin "sound/direct_sound_samples/cries/cry_ledyba.bin"

	.align 2
Cry_Ledian:: @ 855CF20
	.incbin "sound/direct_sound_samples/cries/cry_ledian.bin"

	.align 2
Cry_Spinarak:: @ 855D784
	.incbin "sound/direct_sound_samples/cries/cry_spinarak.bin"

	.align 2
Cry_Ariados:: @ 855E4E8
	.incbin "sound/direct_sound_samples/cries/cry_ariados.bin"

	.align 2
Cry_Crobat:: @ 855F13C
	.incbin "sound/direct_sound_samples/cries/cry_crobat.bin"

	.align 2
Cry_Chinchou:: @ 856086C
	.incbin "sound/direct_sound_samples/cries/cry_chinchou.bin"

	.align 2
Cry_Lanturn:: @ 856151C
	.incbin "sound/direct_sound_samples/cries/cry_lanturn.bin"

	.align 2
Cry_Pichu:: @ 8561FA8
	.incbin "sound/direct_sound_samples/cries/cry_pichu.bin"

	.align 2
Cry_Cleffa:: @ 85626FC
	.incbin "sound/direct_sound_samples/cries/cry_cleffa.bin"

	.align 2
Cry_Igglybuff:: @ 8562CEC
	.incbin "sound/direct_sound_samples/cries/cry_igglybuff.bin"

	.align 2
Cry_Togepi:: @ 85633E8
	.incbin "sound/direct_sound_samples/cries/cry_togepi.bin"

	.align 2
Cry_Togetic:: @ 8563ED0
	.incbin "sound/direct_sound_samples/cries/cry_togetic.bin"

	.align 2
Cry_Natu:: @ 85645D0
	.incbin "sound/direct_sound_samples/cries/cry_natu.bin"

	.align 2
Cry_Xatu:: @ 8565060
	.incbin "sound/direct_sound_samples/cries/cry_xatu.bin"

	.align 2
Cry_Mareep:: @ 8565F2C
	.incbin "sound/direct_sound_samples/cries/cry_mareep.bin"

	.align 2
Cry_Flaaffy:: @ 8566684
	.incbin "sound/direct_sound_samples/cries/cry_flaaffy.bin"

	.align 2
Cry_Ampharos:: @ 8567438
	.incbin "sound/direct_sound_samples/cries/cry_ampharos.bin"

	.align 2
Cry_Bellossom:: @ 85684B8
	.incbin "sound/direct_sound_samples/cries/cry_bellossom.bin"

	.align 2
Cry_Marill:: @ 85692D0
	.incbin "sound/direct_sound_samples/cries/cry_marill.bin"

	.align 2
Cry_Azumarill:: @ 8569FE4
	.incbin "sound/direct_sound_samples/cries/cry_azumarill.bin"

	.align 2
Cry_Sudowoodo:: @ 856B0D0
	.incbin "sound/direct_sound_samples/cries/cry_sudowoodo.bin"

	.align 2
Cry_Politoed:: @ 856C100
	.incbin "sound/direct_sound_samples/cries/cry_politoed.bin"

	.align 2
Cry_Hoppip:: @ 856D344
	.incbin "sound/direct_sound_samples/cries/cry_hoppip.bin"

	.align 2
Cry_Skiploom:: @ 856DBB0
	.incbin "sound/direct_sound_samples/cries/cry_skiploom.bin"

	.align 2
Cry_Jumpluff:: @ 856E8B8
	.incbin "sound/direct_sound_samples/cries/cry_jumpluff.bin"

	.align 2
Cry_Aipom:: @ 856F8F4
	.incbin "sound/direct_sound_samples/cries/cry_aipom.bin"

	.align 2
Cry_Sunkern:: @ 8570714
	.incbin "sound/direct_sound_samples/cries/cry_sunkern.bin"

	.align 2
Cry_Sunflora:: @ 8570F28
	.incbin "sound/direct_sound_samples/cries/cry_sunflora.bin"

	.align 2
Cry_Yanma:: @ 8571F08
	.incbin "sound/direct_sound_samples/cries/cry_yanma.bin"

	.align 2
Cry_Wooper:: @ 8573010
	.incbin "sound/direct_sound_samples/cries/cry_wooper.bin"

	.align 2
Cry_Quagsire:: @ 8573770
	.incbin "sound/direct_sound_samples/cries/cry_quagsire.bin"

	.align 2
Cry_Espeon:: @ 85744D0
	.incbin "sound/direct_sound_samples/cries/cry_espeon.bin"

	.align 2
Cry_Umbreon:: @ 8575884
	.incbin "sound/direct_sound_samples/cries/cry_umbreon.bin"

	.align 2
Cry_Murkrow:: @ 8576804
	.incbin "sound/direct_sound_samples/cries/cry_murkrow.bin"

	.align 2
Cry_Slowking:: @ 85778C8
	.incbin "sound/direct_sound_samples/cries/cry_slowking.bin"

	.align 2
Cry_Misdreavus:: @ 85790AC
	.incbin "sound/direct_sound_samples/cries/cry_misdreavus.bin"

	.align 2
Cry_Unown:: @ 8579C4C
	.incbin "sound/direct_sound_samples/cries/cry_unown.bin"

	.align 2
Cry_Wobbuffet:: @ 857A974
	.incbin "sound/direct_sound_samples/cries/cry_wobbuffet.bin"

	.align 2
Cry_Girafarig:: @ 857BE10
	.incbin "sound/direct_sound_samples/cries/cry_girafarig.bin"

	.align 2
Cry_Pineco:: @ 857CCC4
	.incbin "sound/direct_sound_samples/cries/cry_pineco.bin"

	.align 2
Cry_Forretress:: @ 857DA24
	.incbin "sound/direct_sound_samples/cries/cry_forretress.bin"

	.align 2
Cry_Dunsparce:: @ 857EE2C
	.incbin "sound/direct_sound_samples/cries/cry_dunsparce.bin"

	.align 2
Cry_Gligar:: @ 857FE0C
	.incbin "sound/direct_sound_samples/cries/cry_gligar.bin"

	.align 2
Cry_Steelix:: @ 8580A2C
	.incbin "sound/direct_sound_samples/cries/cry_steelix.bin"

	.align 2
Cry_Snubbull:: @ 8583054
	.incbin "sound/direct_sound_samples/cries/cry_snubbull.bin"

	.align 2
Cry_Granbull:: @ 8583EC8
	.incbin "sound/direct_sound_samples/cries/cry_granbull.bin"

	.align 2
Cry_Qwilfish:: @ 858566C
	.incbin "sound/direct_sound_samples/cries/cry_qwilfish.bin"

	.align 2
Cry_Scizor:: @ 8586208
	.incbin "sound/direct_sound_samples/cries/cry_scizor.bin"

	.align 2
Cry_Shuckle:: @ 8587904
	.incbin "sound/direct_sound_samples/cries/cry_shuckle.bin"

	.align 2
Cry_Heracross:: @ 8588338
	.incbin "sound/direct_sound_samples/cries/cry_heracross.bin"

	.align 2
Cry_Sneasel:: @ 858958C
	.incbin "sound/direct_sound_samples/cries/cry_sneasel.bin"

	.align 2
Cry_Teddiursa:: @ 8589EB0
	.incbin "sound/direct_sound_samples/cries/cry_teddiursa.bin"

	.align 2
Cry_Ursaring:: @ 858AF3C
	.incbin "sound/direct_sound_samples/cries/cry_ursaring.bin"

	.align 2
Cry_Slugma:: @ 858CD14
	.incbin "sound/direct_sound_samples/cries/cry_slugma.bin"

	.align 2
Cry_Magcargo:: @ 858DE2C
	.incbin "sound/direct_sound_samples/cries/cry_magcargo.bin"

	.align 2
Cry_Swinub:: @ 858F334
	.incbin "sound/direct_sound_samples/cries/cry_swinub.bin"

	.align 2
Cry_Piloswine:: @ 858FFDC
	.incbin "sound/direct_sound_samples/cries/cry_piloswine.bin"

	.align 2
Cry_Corsola:: @ 8590CD0
	.incbin "sound/direct_sound_samples/cries/cry_corsola.bin"

	.align 2
Cry_Remoraid:: @ 85919B0
	.incbin "sound/direct_sound_samples/cries/cry_remoraid.bin"

	.align 2
Cry_Octillery:: @ 8592440
	.incbin "sound/direct_sound_samples/cries/cry_octillery.bin"

	.align 2
Cry_Delibird:: @ 8593E84
	.incbin "sound/direct_sound_samples/cries/cry_delibird.bin"

	.align 2
Cry_Mantine:: @ 8594EB8
	.incbin "sound/direct_sound_samples/cries/cry_mantine.bin"

	.align 2
Cry_Skarmory:: @ 8595E80
	.incbin "sound/direct_sound_samples/cries/cry_skarmory.bin"

	.align 2
Cry_Houndour:: @ 8597688
	.incbin "sound/direct_sound_samples/cries/cry_houndour.bin"

	.align 2
Cry_Houndoom:: @ 8598330
	.incbin "sound/direct_sound_samples/cries/cry_houndoom.bin"

	.align 2
Cry_Kingdra:: @ 85996E0
	.incbin "sound/direct_sound_samples/cries/cry_kingdra.bin"

	.align 2
Cry_Phanpy:: @ 859A4B8
	.incbin "sound/direct_sound_samples/cries/cry_phanpy.bin"

	.align 2
Cry_Donphan:: @ 859B008
	.incbin "sound/direct_sound_samples/cries/cry_donphan.bin"

	.align 2
Cry_Porygon2:: @ 859C12C
	.incbin "sound/direct_sound_samples/cries/cry_porygon2.bin"

	.align 2
Cry_Stantler:: @ 859D0E4
	.incbin "sound/direct_sound_samples/cries/cry_stantler.bin"

	.align 2
Cry_Smeargle:: @ 859E760
	.incbin "sound/direct_sound_samples/cries/cry_smeargle.bin"

	.align 2
Cry_Tyrogue:: @ 859F194
	.incbin "sound/direct_sound_samples/cries/cry_tyrogue.bin"

	.align 2
Cry_Hitmontop:: @ 85A01BC
	.incbin "sound/direct_sound_samples/cries/cry_hitmontop.bin"

	.align 2
Cry_Smoochum:: @ 85A0F9C
	.incbin "sound/direct_sound_samples/cries/cry_smoochum.bin"

	.align 2
Cry_Elekid:: @ 85A1B50
	.incbin "sound/direct_sound_samples/cries/cry_elekid.bin"

	.align 2
Cry_Magby:: @ 85A25DC
	.incbin "sound/direct_sound_samples/cries/cry_magby.bin"

	.align 2
Cry_Miltank:: @ 85A344C
	.incbin "sound/direct_sound_samples/cries/cry_miltank.bin"

	.align 2
Cry_Blissey:: @ 85A4328
	.incbin "sound/direct_sound_samples/cries/cry_blissey.bin"

	.align 2
Cry_Raikou:: @ 85A53BC
	.incbin "sound/direct_sound_samples/cries/cry_raikou.bin"

	.align 2
Cry_Entei:: @ 85A652C
	.incbin "sound/direct_sound_samples/cries/cry_entei.bin"

	.align 2
Cry_Suicune:: @ 85A79A0
	.incbin "sound/direct_sound_samples/cries/cry_suicune.bin"

	.align 2
Cry_Larvitar:: @ 85A8BE8
	.incbin "sound/direct_sound_samples/cries/cry_larvitar.bin"

	.align 2
Cry_Pupitar:: @ 85A9898
	.incbin "sound/direct_sound_samples/cries/cry_pupitar.bin"

	.align 2
Cry_Tyranitar:: @ 85AA108
	.incbin "sound/direct_sound_samples/cries/cry_tyranitar.bin"

	.align 2
Cry_Lugia:: @ 85AB868
	.incbin "sound/direct_sound_samples/cries/cry_lugia.bin"

	.align 2
Cry_HoOh:: @ 85ADE60
	.incbin "sound/direct_sound_samples/cries/cry_ho_oh.bin"

	.align 2
Cry_Celebi:: @ 85AF4F4
	.incbin "sound/direct_sound_samples/cries/cry_celebi.bin"

	.align 2
Cry_Kecleon:: @ 85B036C
	.incbin "sound/direct_sound_samples/cries/cry_kecleon.bin"

	.align 2
Cry_Roselia:: @ 85B0BCC
	.incbin "sound/direct_sound_samples/cries/cry_roselia.bin"

	.align 2
Cry_Torkoal:: @ 85B168C
	.incbin "sound/direct_sound_samples/cries/cry_torkoal.bin"

	.align 2
Cry_Electrike:: @ 85B1FD8
	.incbin "sound/direct_sound_samples/cries/cry_electrike.bin"

	.align 2
Cry_Manectric:: @ 85B2C34
	.incbin "sound/direct_sound_samples/cries/cry_manectric.bin"

	.align 2
Cry_Duskull:: @ 85B413C
	.incbin "sound/direct_sound_samples/cries/cry_duskull.bin"

	.align 2
Cry_Latias:: @ 85B4BD4
	.incbin "sound/direct_sound_samples/cries/cry_latias.bin"

	.align 2
Cry_Wynaut:: @ 85B5804
	.incbin "sound/direct_sound_samples/cries/cry_wynaut.bin"

	.align 2
Cry_Seviper:: @ 85B65E4
	.incbin "sound/direct_sound_samples/cries/cry_seviper.bin"

	.align 2
Cry_Sharpedo:: @ 85B7184
	.incbin "sound/direct_sound_samples/cries/cry_sharpedo.bin"

	.align 2
Cry_Zangoose:: @ 85B8890
	.incbin "sound/direct_sound_samples/cries/cry_zangoose.bin"

	.align 2
Cry_Azurill:: @ 85B9220
	.incbin "sound/direct_sound_samples/cries/cry_azurill.bin"

	.align 2
Cry_Swablu:: @ 85B9C88
	.incbin "sound/direct_sound_samples/cries/cry_swablu.bin"

	.align 2
Cry_Altaria:: @ 85BA220
	.incbin "sound/direct_sound_samples/cries/cry_altaria.bin"

	.align 2
Cry_Unused265:: @ 85BAD3C
	.incbin "sound/direct_sound_samples/cries/cry_unused_265.bin"

	.align 2
Cry_Taillow:: @ 85BB690
	.incbin "sound/direct_sound_samples/cries/cry_taillow.bin"

	.align 2
Cry_Swellow:: @ 85BBC90
	.incbin "sound/direct_sound_samples/cries/cry_swellow.bin"

	.align 2
Cry_Unused268:: @ 85BC594
	.incbin "sound/direct_sound_samples/cries/cry_unused_268.bin"

	.align 2
Cry_Spinda:: @ 85BD744
	.incbin "sound/direct_sound_samples/cries/cry_spinda.bin"

	.align 2
Cry_Torchic:: @ 85BE3B0
	.incbin "sound/direct_sound_samples/cries/cry_torchic.bin"

	.align 2
Cry_Combusken:: @ 85BED58
	.incbin "sound/direct_sound_samples/cries/cry_combusken.bin"

	.align 2
Cry_Blaziken:: @ 85C0A2C
	.incbin "sound/direct_sound_samples/cries/cry_blaziken.bin"

	.align 2
Cry_Treecko:: @ 85C29AC
	.incbin "sound/direct_sound_samples/cries/cry_treecko.bin"

	.align 2
Cry_Grovyle:: @ 85C3554
	.incbin "sound/direct_sound_samples/cries/cry_grovyle.bin"

	.align 2
Cry_Sceptile:: @ 85C49C8
	.incbin "sound/direct_sound_samples/cries/cry_sceptile.bin"

	.align 2
Cry_Mudkip:: @ 85C63E4
	.incbin "sound/direct_sound_samples/cries/cry_mudkip.bin"

	.align 2
Cry_Marshtomp:: @ 85C6B68
	.incbin "sound/direct_sound_samples/cries/cry_marshtomp.bin"

	.align 2
Cry_Swampert:: @ 85C7C6C
	.incbin "sound/direct_sound_samples/cries/cry_swampert.bin"

	.align 2
Cry_Pelipper:: @ 85C92EC
	.incbin "sound/direct_sound_samples/cries/cry_pelipper.bin"

	.align 2
Cry_Wingull:: @ 85C9EB4
	.incbin "sound/direct_sound_samples/cries/cry_wingull.bin"

	.align 2
Cry_Banette:: @ 85CAAF4
	.incbin "sound/direct_sound_samples/cries/cry_banette.bin"

	.align 2
Cry_Shuppet:: @ 85CB79C
	.incbin "sound/direct_sound_samples/cries/cry_shuppet.bin"

	.align 2
Cry_Lotad:: @ 85CBFDC
	.incbin "sound/direct_sound_samples/cries/cry_lotad.bin"

	.align 2
Cry_Lombre:: @ 85CC444
	.incbin "sound/direct_sound_samples/cries/cry_lombre.bin"

	.align 2
Cry_Ludicolo:: @ 85CD2D8
	.incbin "sound/direct_sound_samples/cries/cry_ludicolo.bin"

	.align 2
Cry_Seedot:: @ 85CE3A8
	.incbin "sound/direct_sound_samples/cries/cry_seedot.bin"

	.align 2
Cry_Nuzleaf:: @ 85CEBD4
	.incbin "sound/direct_sound_samples/cries/cry_nuzleaf.bin"

	.align 2
Cry_Shiftry:: @ 85CF73C
	.incbin "sound/direct_sound_samples/cries/cry_shiftry.bin"

	.align 2
Cry_Carvanha:: @ 85D0B00
	.incbin "sound/direct_sound_samples/cries/cry_carvanha.bin"

	.align 2
Cry_Wurmple:: @ 85D1514
	.incbin "sound/direct_sound_samples/cries/cry_wurmple.bin"

	.align 2
Cry_Silcoon:: @ 85D1DE0
	.incbin "sound/direct_sound_samples/cries/cry_silcoon.bin"

	.align 2
Cry_Beautifly:: @ 85D2E0C
	.incbin "sound/direct_sound_samples/cries/cry_beautifly.bin"

	.align 2
Cry_Cascoon:: @ 85D3644
	.incbin "sound/direct_sound_samples/cries/cry_cascoon.bin"

	.align 2
Cry_Dustox:: @ 85D4688
	.incbin "sound/direct_sound_samples/cries/cry_dustox.bin"

	.align 2
Cry_Ralts:: @ 85D5334
	.incbin "sound/direct_sound_samples/cries/cry_ralts.bin"

	.align 2
Cry_Kirlia:: @ 85D5D50
	.incbin "sound/direct_sound_samples/cries/cry_kirlia.bin"

	.align 2
Cry_Gardevoir:: @ 85D6980
	.incbin "sound/direct_sound_samples/cries/cry_gardevoir.bin"

	.align 2
Cry_Slakoth:: @ 85D81E4
	.incbin "sound/direct_sound_samples/cries/cry_slakoth.bin"

	.align 2
Cry_Vigoroth:: @ 85D8A68
	.incbin "sound/direct_sound_samples/cries/cry_vigoroth.bin"

	.align 2
Cry_Slaking:: @ 85D98C0
	.incbin "sound/direct_sound_samples/cries/cry_slaking.bin"

	.align 2
Cry_Nincada:: @ 85DA2AC
	.incbin "sound/direct_sound_samples/cries/cry_nincada.bin"

	.align 2
Cry_Ninjask:: @ 85DA91C
	.incbin "sound/direct_sound_samples/cries/cry_ninjask.bin"

	.align 2
Cry_Shedinja:: @ 85DB544
	.incbin "sound/direct_sound_samples/cries/cry_shedinja.bin"

	.align 2
Cry_Makuhita:: @ 85DBCFC
	.incbin "sound/direct_sound_samples/cries/cry_makuhita.bin"

	.align 2
Cry_Hariyama:: @ 85DC458
	.incbin "sound/direct_sound_samples/cries/cry_hariyama.bin"

	.align 2
Cry_Nosepass:: @ 85DD510
	.incbin "sound/direct_sound_samples/cries/cry_nosepass.bin"

	.align 2
Cry_Glalie:: @ 85DE274
	.incbin "sound/direct_sound_samples/cries/cry_glalie.bin"

	.align 2
Cry_Plusle:: @ 85DF758
	.incbin "sound/direct_sound_samples/cries/cry_plusle.bin"

	.align 2
Cry_Minun:: @ 85E0054
	.incbin "sound/direct_sound_samples/cries/cry_minun.bin"

	.align 2
Cry_Surskit:: @ 85E105C
	.incbin "sound/direct_sound_samples/cries/cry_surskit.bin"

	.align 2
Cry_Masquerain:: @ 85E1ADC
	.incbin "sound/direct_sound_samples/cries/cry_masquerain.bin"

	.align 2
Cry_Skitty:: @ 85E2E90
	.incbin "sound/direct_sound_samples/cries/cry_skitty.bin"

	.align 2
Cry_Delcatty:: @ 85E35A4
	.incbin "sound/direct_sound_samples/cries/cry_delcatty.bin"

	.align 2
Cry_Gulpin:: @ 85E4ABC
	.incbin "sound/direct_sound_samples/cries/cry_gulpin.bin"

	.align 2
Cry_Swalot:: @ 85E52C0
	.incbin "sound/direct_sound_samples/cries/cry_swalot.bin"

	.align 2
Cry_Numel:: @ 85E6420
	.incbin "sound/direct_sound_samples/cries/cry_numel.bin"

	.align 2
Cry_Camerupt:: @ 85E6D6C
	.incbin "sound/direct_sound_samples/cries/cry_camerupt.bin"

	.align 2
Cry_Barboach:: @ 85E848C
	.incbin "sound/direct_sound_samples/cries/cry_barboach.bin"

	.align 2
Cry_Whiscash:: @ 85E8DC8
	.incbin "sound/direct_sound_samples/cries/cry_whiscash.bin"

	.align 2
Cry_Corphish:: @ 85E9EC4
	.incbin "sound/direct_sound_samples/cries/cry_corphish.bin"

	.align 2
Cry_Crawdaunt:: @ 85EAAC8
	.incbin "sound/direct_sound_samples/cries/cry_crawdaunt.bin"

	.align 2
Cry_Spoink:: @ 85EC380
	.incbin "sound/direct_sound_samples/cries/cry_spoink.bin"

	.align 2
Cry_Grumpig:: @ 85ECAC0
	.incbin "sound/direct_sound_samples/cries/cry_grumpig.bin"

	.align 2
Cry_Trapinch:: @ 85ED760
	.incbin "sound/direct_sound_samples/cries/cry_trapinch.bin"

	.align 2
Cry_Vibrava:: @ 85EE184
	.incbin "sound/direct_sound_samples/cries/cry_vibrava.bin"

	.align 2
Cry_Flygon:: @ 85EEF88
	.incbin "sound/direct_sound_samples/cries/cry_flygon.bin"

	.align 2
Cry_Cacnea:: @ 85F0990
	.incbin "sound/direct_sound_samples/cries/cry_cacnea.bin"

	.align 2
Cry_Cacturne:: @ 85F1280
	.incbin "sound/direct_sound_samples/cries/cry_cacturne.bin"

	.align 2
Cry_Baltoy:: @ 85F2930
	.incbin "sound/direct_sound_samples/cries/cry_baltoy.bin"

	.align 2
Cry_Claydol:: @ 85F35B4
	.incbin "sound/direct_sound_samples/cries/cry_claydol.bin"

	.align 2
Cry_Lunatone:: @ 85F4914
	.incbin "sound/direct_sound_samples/cries/cry_lunatone.bin"

	.align 2
Cry_Solrock:: @ 85F6110
	.incbin "sound/direct_sound_samples/cries/cry_solrock.bin"

	.align 2
Cry_Feebas:: @ 85F713C
	.incbin "sound/direct_sound_samples/cries/cry_feebas.bin"

	.align 2
Cry_Milotic:: @ 85F7910
	.incbin "sound/direct_sound_samples/cries/cry_milotic.bin"

	.align 2
Cry_Absol:: @ 85FA054
	.incbin "sound/direct_sound_samples/cries/cry_absol.bin"

	.align 2
Cry_Meditite:: @ 85FAAD0
	.incbin "sound/direct_sound_samples/cries/cry_meditite.bin"

	.align 2
Cry_Medicham:: @ 85FB2F0
	.incbin "sound/direct_sound_samples/cries/cry_medicham.bin"

	.align 2
Cry_Spheal:: @ 85FC374
	.incbin "sound/direct_sound_samples/cries/cry_spheal.bin"

	.align 2
Cry_Sealeo:: @ 85FC928
	.incbin "sound/direct_sound_samples/cries/cry_sealeo.bin"

	.align 2
Cry_Walrein:: @ 85FD500
	.incbin "sound/direct_sound_samples/cries/cry_walrein.bin"

	.align 2
Cry_Clamperl:: @ 85FF94C
	.incbin "sound/direct_sound_samples/cries/cry_clamperl.bin"

	.align 2
Cry_Huntail:: @ 8600B9C
	.incbin "sound/direct_sound_samples/cries/cry_huntail.bin"

	.align 2
Cry_Gorebyss:: @ 8601B84
	.incbin "sound/direct_sound_samples/cries/cry_gorebyss.bin"

	.align 2
Cry_Lileep:: @ 86031F0
	.incbin "sound/direct_sound_samples/cries/cry_lileep.bin"

	.align 2
Cry_Cradily:: @ 8603B98
	.incbin "sound/direct_sound_samples/cries/cry_cradily.bin"

	.align 2
Cry_Anorith:: @ 86058C8
	.incbin "sound/direct_sound_samples/cries/cry_anorith.bin"

	.align 2
Cry_Armaldo:: @ 8606480
	.incbin "sound/direct_sound_samples/cries/cry_armaldo.bin"

	.align 2
Cry_Beldum:: @ 8607B54
	.incbin "sound/direct_sound_samples/cries/cry_beldum.bin"

	.align 2
Cry_Metang:: @ 86084F4
	.incbin "sound/direct_sound_samples/cries/cry_metang.bin"

	.align 2
Cry_Metagross:: @ 86097C8
	.incbin "sound/direct_sound_samples/cries/cry_metagross.bin"

	.align 2
Cry_Bagon:: @ 860BF40
	.incbin "sound/direct_sound_samples/cries/cry_bagon.bin"

	.align 2
Cry_Shelgon:: @ 860C714
	.incbin "sound/direct_sound_samples/cries/cry_shelgon.bin"

	.align 2
Cry_Regirock:: @ 860DB1C
	.incbin "sound/direct_sound_samples/cries/cry_regirock.bin"

	.align 2
Cry_Regice:: @ 860FAF8
	.incbin "sound/direct_sound_samples/cries/cry_regice.bin"

	.align 2
Cry_Registeel:: @ 8611AF8
	.incbin "sound/direct_sound_samples/cries/cry_registeel.bin"

	.align 2
Cry_Castform:: @ 86131FC
	.incbin "sound/direct_sound_samples/cries/cry_castform.bin"

	.align 2
Cry_Volbeat:: @ 8613E94
	.incbin "sound/direct_sound_samples/cries/cry_volbeat.bin"

	.align 2
Cry_Illumise:: @ 8614A1C
	.incbin "sound/direct_sound_samples/cries/cry_illumise.bin"

	.align 2
Cry_Poochyena:: @ 8615B34
	.incbin "sound/direct_sound_samples/cries/cry_poochyena.bin"

	.align 2
Cry_Mightyena:: @ 861647C
	.incbin "sound/direct_sound_samples/cries/cry_mightyena.bin"

	.align 2
Cry_Dusclops:: @ 8617808
	.incbin "sound/direct_sound_samples/cries/cry_dusclops.bin"

	.align 2
Cry_Sableye:: @ 86185C0
	.incbin "sound/direct_sound_samples/cries/cry_sableye.bin"

	.align 2
Cry_Mawile:: @ 8619164
	.incbin "sound/direct_sound_samples/cries/cry_mawile.bin"

	.align 2
Cry_Aron:: @ 8619CE4
	.incbin "sound/direct_sound_samples/cries/cry_aron.bin"

	.align 2
Cry_Lairon:: @ 861A610
	.incbin "sound/direct_sound_samples/cries/cry_lairon.bin"

	.align 2
Cry_Aggron:: @ 861BAE8
	.incbin "sound/direct_sound_samples/cries/cry_aggron.bin"

	.align 2
Cry_Relicanth:: @ 861D48C
	.incbin "sound/direct_sound_samples/cries/cry_relicanth.bin"

	.align 2
Cry_Luvdisc:: @ 861E8BC
	.incbin "sound/direct_sound_samples/cries/cry_luvdisc.bin"

	.align 2
Cry_Groudon:: @ 861ED98
	.incbin "sound/direct_sound_samples/cries/cry_groudon.bin"

	.align 2
Cry_Kyogre:: @ 86212A4
	.incbin "sound/direct_sound_samples/cries/cry_kyogre.bin"

	.align 2
Cry_Rayquaza:: @ 862365C
	.incbin "sound/direct_sound_samples/cries/cry_rayquaza.bin"

	.align 2
Cry_Salamence:: @ 8625388
	.incbin "sound/direct_sound_samples/cries/cry_salamence.bin"

	.align 2
Cry_Breloom:: @ 8626CA4
	.incbin "sound/direct_sound_samples/cries/cry_breloom.bin"

	.align 2
Cry_Shroomish:: @ 8627964
	.incbin "sound/direct_sound_samples/cries/cry_shroomish.bin"

	.align 2
Cry_Linoone:: @ 862823C
	.incbin "sound/direct_sound_samples/cries/cry_linoone.bin"

	.align 2
Cry_Tropius:: @ 862A0D8
	.incbin "sound/direct_sound_samples/cries/cry_tropius.bin"

	.align 2
Cry_Wailmer:: @ 862C19C
	.incbin "sound/direct_sound_samples/cries/cry_wailmer.bin"

	.align 2
Cry_Zigzagoon:: @ 862DDFC
	.incbin "sound/direct_sound_samples/cries/cry_zigzagoon.bin"

	.align 2
Cry_Exploud:: @ 862E98C
	.incbin "sound/direct_sound_samples/cries/cry_exploud.bin"

	.align 2
Cry_Loudred:: @ 86305D4
	.incbin "sound/direct_sound_samples/cries/cry_loudred.bin"

	.align 2
Cry_Wailord:: @ 86312FC
	.incbin "sound/direct_sound_samples/cries/cry_wailord.bin"

	.align 2
Cry_Whismur:: @ 8633D0C
	.incbin "sound/direct_sound_samples/cries/cry_whismur.bin"

	.align 2
Cry_Snorunt:: @ 8634530
	.incbin "sound/direct_sound_samples/cries/cry_snorunt.bin"

	.align 2
Cry_Latios:: @ 8635638
	.incbin "sound/direct_sound_samples/cries/cry_latios.bin"

	.align 2
Cry_Jirachi:: @ 8636C30
	.incbin "sound/direct_sound_samples/cries/cry_jirachi.bin"

	.align 2
Cry_Deoxys:: @ 86379B4
	.incbin "sound/direct_sound_samples/cries/cry_deoxys.bin"

	.align 2
Cry_Chimecho:: @ 8638E88
	.incbin "sound/direct_sound_samples/cries/cry_chimecho.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel7:: @ 8639898
	.incbin "sound/direct_sound_samples/phonemes/vowel_7.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel8:: @ 8639EF8
	.incbin "sound/direct_sound_samples/phonemes/vowel_8.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel9:: @ 863A3DC
	.incbin "sound/direct_sound_samples/phonemes/vowel_9.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel10:: @ 863AD2C
	.incbin "sound/direct_sound_samples/phonemes/vowel_10.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel11:: @ 863B79C
	.incbin "sound/direct_sound_samples/phonemes/vowel_11.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel12:: @ 863BABC
	.incbin "sound/direct_sound_samples/phonemes/vowel_12.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel13:: @ 863C744
	.incbin "sound/direct_sound_samples/phonemes/vowel_13.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel14:: @ 863CD64
	.incbin "sound/direct_sound_samples/phonemes/vowel_14.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel15:: @ 863D0EC
	.incbin "sound/direct_sound_samples/phonemes/vowel_15.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel16:: @ 863DED0
	.incbin "sound/direct_sound_samples/phonemes/vowel_16.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel17:: @ 863E840
	.incbin "sound/direct_sound_samples/phonemes/vowel_17.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel18:: @ 863EBDC
	.incbin "sound/direct_sound_samples/phonemes/vowel_18.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel19:: @ 863F390
	.incbin "sound/direct_sound_samples/phonemes/vowel_19.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel20:: @ 86400EC
	.incbin "sound/direct_sound_samples/phonemes/vowel_20.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel21:: @ 8640330
	.incbin "sound/direct_sound_samples/phonemes/vowel_21.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel22:: @ 8641170
	.incbin "sound/direct_sound_samples/phonemes/vowel_22.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel23:: @ 8641AC4
	.incbin "sound/direct_sound_samples/phonemes/vowel_23.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel24:: @ 8641E18
	.incbin "sound/direct_sound_samples/phonemes/vowel_24.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel25:: @ 864244C
	.incbin "sound/direct_sound_samples/phonemes/vowel_25.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel26:: @ 86430B8
	.incbin "sound/direct_sound_samples/phonemes/vowel_26.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel27:: @ 8643650
	.incbin "sound/direct_sound_samples/phonemes/vowel_27.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel28:: @ 8644154
	.incbin "sound/direct_sound_samples/phonemes/vowel_28.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel29:: @ 8644758
	.incbin "sound/direct_sound_samples/phonemes/vowel_29.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel30:: @ 8644950
	.incbin "sound/direct_sound_samples/phonemes/vowel_30.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel31:: @ 86452B4
	.incbin "sound/direct_sound_samples/phonemes/vowel_31.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel32:: @ 8646240
	.incbin "sound/direct_sound_samples/phonemes/vowel_32.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel33:: @ 8646878
	.incbin "sound/direct_sound_samples/phonemes/vowel_33.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel34:: @ 864734C
	.incbin "sound/direct_sound_samples/phonemes/vowel_34.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel35:: @ 8648290
	.incbin "sound/direct_sound_samples/phonemes/vowel_35.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel36:: @ 8648808
	.incbin "sound/direct_sound_samples/phonemes/vowel_36.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel37:: @ 8649654
	.incbin "sound/direct_sound_samples/phonemes/vowel_37.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel38:: @ 864A55C
	.incbin "sound/direct_sound_samples/phonemes/vowel_38.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel39:: @ 864B030
	.incbin "sound/direct_sound_samples/phonemes/vowel_39.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel40:: @ 864BBC4
	.incbin "sound/direct_sound_samples/phonemes/vowel_40.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel41:: @ 864C59C
	.incbin "sound/direct_sound_samples/phonemes/vowel_41.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel42:: @ 864CBDC
	.incbin "sound/direct_sound_samples/phonemes/vowel_42.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel43:: @ 864D6BC
	.incbin "sound/direct_sound_samples/phonemes/vowel_43.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel44:: @ 864DCF8
	.incbin "sound/direct_sound_samples/phonemes/vowel_44.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel45:: @ 864E410
	.incbin "sound/direct_sound_samples/phonemes/vowel_45.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel46:: @ 864ED4C
	.incbin "sound/direct_sound_samples/phonemes/vowel_46.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel47:: @ 864F508
	.incbin "sound/direct_sound_samples/phonemes/vowel_47.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel48:: @ 864FA6C
	.incbin "sound/direct_sound_samples/phonemes/vowel_48.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel49:: @ 86507E0
	.incbin "sound/direct_sound_samples/phonemes/vowel_49.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel50:: @ 8650C5C
	.incbin "sound/direct_sound_samples/phonemes/vowel_50.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel51:: @ 8651148
	.incbin "sound/direct_sound_samples/phonemes/vowel_51.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel52:: @ 8651910
	.incbin "sound/direct_sound_samples/phonemes/vowel_52.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel53:: @ 865250C
	.incbin "sound/direct_sound_samples/phonemes/vowel_53.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel54:: @ 8652884
	.incbin "sound/direct_sound_samples/phonemes/vowel_54.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel55:: @ 8653040
	.incbin "sound/direct_sound_samples/phonemes/vowel_55.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel56:: @ 8653CA4
	.incbin "sound/direct_sound_samples/phonemes/vowel_56.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel57:: @ 8654170
	.incbin "sound/direct_sound_samples/phonemes/vowel_57.bin"

	.align 2
DirectSoundWaveData_SC88_AccordionFr_Copy:: @ 8654C20
	.incbin "sound/direct_sound_samples/synth/sc88_22_accordion_fr.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cries/cry_abomasnow.bin"

	.align 2
Cry_Accelgor::
	.incbin "sound/direct_sound_samples/cries/cry_accelgor.bin"

	.align 2
Cry_Aegislash::
	.incbin "sound/direct_sound_samples/cries/cry_aegislash.bin"

	.align 2
Cry_Alomomola::
	.incbin "sound/direct_sound_samples/cries/cry_alomomola.bin"

	.align 2
Cry_Amaura::
	.incbin "sound/direct_sound_samples/cries/cry_amaura.bin"

	.align 2
Cry_Ambipom::
	.incbin "sound/direct_sound_samples/cries/cry_ambipom.bin"

	.align 2
Cry_Amoonguss::
	.incbin "sound/direct_sound_samples/cries/cry_amoonguss.bin"

	.align 2
Cry_Araquanid::
	.incbin "sound/direct_sound_samples/cries/cry_araquanid.bin"

	.align 2
Cry_Arceus::
	.incbin "sound/direct_sound_samples/cries/cry_arceus.bin"

	.align 2
Cry_Archen::
	.incbin "sound/direct_sound_samples/cries/cry_archen.bin"

	.align 2
Cry_Archeops::
	.incbin "sound/direct_sound_samples/cries/cry_archeops.bin"

	.align 2
Cry_Aromatisse::
	.incbin "sound/direct_sound_samples/cries/cry_aromatisse.bin"

	.align 2
Cry_Audino::
	.incbin "sound/direct_sound_samples/cries/cry_audino.bin"

	.align 2
Cry_Aurorus::
	.incbin "sound/direct_sound_samples/cries/cry_aurorus.bin"

	.align 2
Cry_Avalugg::
	.incbin "sound/direct_sound_samples/cries/cry_avalugg.bin"

	.align 2
Cry_Axew::
	.incbin "sound/direct_sound_samples/cries/cry_axew.bin"

	.align 2
Cry_Azelf::
	.incbin "sound/direct_sound_samples/cries/cry_azelf.bin"

	.align 2
Cry_Barbaracle::
	.incbin "sound/direct_sound_samples/cries/cry_barbaracle.bin"

	.align 2
Cry_Basculin::
	.incbin "sound/direct_sound_samples/cries/cry_basculin.bin"

	.align 2
Cry_Bastiodon::
	.incbin "sound/direct_sound_samples/cries/cry_bastiodon.bin"

	.align 2
Cry_Beartic::
	.incbin "sound/direct_sound_samples/cries/cry_beartic.bin"

	.align 2
Cry_Beheeyem::
	.incbin "sound/direct_sound_samples/cries/cry_beheeyem.bin"

	.align 2
Cry_Bergmite::
	.incbin "sound/direct_sound_samples/cries/cry_bergmite.bin"

	.align 2
Cry_Bewear::
	.incbin "sound/direct_sound_samples/cries/cry_bewear.bin"

	.align 2
Cry_Bibarel::
	.incbin "sound/direct_sound_samples/cries/cry_bibarel.bin"

	.align 2
Cry_Bidoof::
	.incbin "sound/direct_sound_samples/cries/cry_bidoof.bin"

	.align 2
Cry_Binacle::
	.incbin "sound/direct_sound_samples/cries/cry_binacle.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cries/cry_bisharp.bin"

	.align 2
Cry_Blacephalon::
	.incbin "sound/direct_sound_samples/cries/cry_blacephalon.bin"

	.align 2
Cry_Blitzle::
	.incbin "sound/direct_sound_samples/cries/cry_blitzle.bin"

	.align 2
Cry_Boldore::
	.incbin "sound/direct_sound_samples/cries/cry_boldore.bin"

	.align 2
Cry_Bonsly::
	.incbin "sound/direct_sound_samples/cries/cry_bonsly.bin"

	.align 2
Cry_Bouffalant::
	.incbin "sound/direct_sound_samples/cries/cry_bouffalant.bin"

	.align 2
Cry_Bounsweet::
	.incbin "sound/direct_sound_samples/cries/cry_bounsweet.bin"

	.align 2
Cry_Braixen::
	.incbin "sound/direct_sound_samples/cries/cry_braixen.bin"

	.align 2
Cry_Braviary::
	.incbin "sound/direct_sound_samples/cries/cry_braviary.bin"

	.align 2
Cry_Brionne::
	.incbin "sound/direct_sound_samples/cries/cry_brionne.bin"

	.align 2
Cry_Bronzong::
	.incbin "sound/direct_sound_samples/cries/cry_bronzong.bin"

	.align 2
Cry_Bronzor::
	.incbin "sound/direct_sound_samples/cries/cry_bronzor.bin"

	.align 2
Cry_Bruxish::
	.incbin "sound/direct_sound_samples/cries/cry_bruxish.bin"

	.align 2
Cry_Budew::
	.incbin "sound/direct_sound_samples/cries/cry_budew.bin"

	.align 2
Cry_Buizel::
	.incbin "sound/direct_sound_samples/cries/cry_buizel.bin"

	.align 2
Cry_Buneary::
	.incbin "sound/direct_sound_samples/cries/cry_buneary.bin"

	.align 2
Cry_Bunnelby::
	.incbin "sound/direct_sound_samples/cries/cry_bunnelby.bin"

	.align 2
Cry_Burmy::
	.incbin "sound/direct_sound_samples/cries/cry_burmy.bin"

	.align 2
Cry_Buzzwole::
	.incbin "sound/direct_sound_samples/cries/cry_buzzwole.bin"

	.align 2
Cry_Carbink::
	.incbin "sound/direct_sound_samples/cries/cry_carbink.bin"

	.align 2
Cry_Carnivine::
	.incbin "sound/direct_sound_samples/cries/cry_carnivine.bin"

	.align 2
Cry_Carracosta::
	.incbin "sound/direct_sound_samples/cries/cry_carracosta.bin"

	.align 2
Cry_Celesteela::
	.incbin "sound/direct_sound_samples/cries/cry_celesteela.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cries/cry_chandelure.bin"

	.align 2
Cry_Charjabug::
	.incbin "sound/direct_sound_samples/cries/cry_charjabug.bin"

	.align 2
Cry_Chatot::
	.incbin "sound/direct_sound_samples/cries/cry_chatot.bin"

	.align 2
Cry_Cherrim::
	.incbin "sound/direct_sound_samples/cries/cry_cherrim.bin"

	.align 2
Cry_Cherubi::
	.incbin "sound/direct_sound_samples/cries/cry_cherubi.bin"

	.align 2
Cry_Chesnaught::
	.incbin "sound/direct_sound_samples/cries/cry_chesnaught.bin"

	.align 2
Cry_Chespin::
	.incbin "sound/direct_sound_samples/cries/cry_chespin.bin"

	.align 2
Cry_Chimchar::
	.incbin "sound/direct_sound_samples/cries/cry_chimchar.bin"

	.align 2
Cry_Chingling::
	.incbin "sound/direct_sound_samples/cries/cry_chingling.bin"

	.align 2
Cry_Cinccino::
	.incbin "sound/direct_sound_samples/cries/cry_cinccino.bin"

	.align 2
Cry_Clauncher::
	.incbin "sound/direct_sound_samples/cries/cry_clauncher.bin"

	.align 2
Cry_Clawitzer::
	.incbin "sound/direct_sound_samples/cries/cry_clawitzer.bin"

	.align 2
Cry_Cobalion::
	.incbin "sound/direct_sound_samples/cries/cry_cobalion.bin"

	.align 2
Cry_Cofagrigus::
	.incbin "sound/direct_sound_samples/cries/cry_cofagrigus.bin"

	.align 2
Cry_Combee::
	.incbin "sound/direct_sound_samples/cries/cry_combee.bin"

	.align 2
Cry_Comfey::
	.incbin "sound/direct_sound_samples/cries/cry_comfey.bin"

	.align 2
Cry_Conkeldurr::
	.incbin "sound/direct_sound_samples/cries/cry_conkeldurr.bin"

	.align 2
Cry_Cosmoem::
	.incbin "sound/direct_sound_samples/cries/cry_cosmoem.bin"

	.align 2
Cry_Cosmog::
	.incbin "sound/direct_sound_samples/cries/cry_cosmog.bin"

	.align 2
Cry_Cottonee::
	.incbin "sound/direct_sound_samples/cries/cry_cottonee.bin"

	.align 2
Cry_Crabominable::
	.incbin "sound/direct_sound_samples/cries/cry_crabominable.bin"

	.align 2
Cry_Crabrawler::
	.incbin "sound/direct_sound_samples/cries/cry_crabrawler.bin"

	.align 2
Cry_Cranidos::
	.incbin "sound/direct_sound_samples/cries/cry_cranidos.bin"

	.align 2
Cry_Cresselia::
	.incbin "sound/direct_sound_samples/cries/cry_cresselia.bin"

	.align 2
Cry_Croagunk::
	.incbin "sound/direct_sound_samples/cries/cry_croagunk.bin"

	.align 2
Cry_Crustle::
	.incbin "sound/direct_sound_samples/cries/cry_crustle.bin"

	.align 2
Cry_Cryogonal::
	.incbin "sound/direct_sound_samples/cries/cry_cryogonal.bin"

	.align 2
Cry_Cubchoo::
	.incbin "sound/direct_sound_samples/cries/cry_cubchoo.bin"

	.align 2
Cry_Cutiefly::
	.incbin "sound/direct_sound_samples/cries/cry_cutiefly.bin"

	.align 2
Cry_Darkrai::
	.incbin "sound/direct_sound_samples/cries/cry_darkrai.bin"

	.align 2
Cry_Darmanitan::
	.incbin "sound/direct_sound_samples/cries/cry_darmanitan.bin"

	.align 2
Cry_Dartrix::
	.incbin "sound/direct_sound_samples/cries/cry_dartrix.bin"

	.align 2
Cry_Darumaka::
	.incbin "sound/direct_sound_samples/cries/cry_darumaka.bin"

	.align 2
Cry_Decidueye::
	.incbin "sound/direct_sound_samples/cries/cry_decidueye.bin"

	.align 2
Cry_Dedenne::
	.incbin "sound/direct_sound_samples/cries/cry_dedenne.bin"

	.align 2
Cry_Deerling::
	.incbin "sound/direct_sound_samples/cries/cry_deerling.bin"

	.align 2
Cry_Deino::
	.incbin "sound/direct_sound_samples/cries/cry_deino.bin"

	.align 2
Cry_Delphox::
	.incbin "sound/direct_sound_samples/cries/cry_delphox.bin"

	.align 2
Cry_Dewott::
	.incbin "sound/direct_sound_samples/cries/cry_dewott.bin"

	.align 2
Cry_Dewpider::
	.incbin "sound/direct_sound_samples/cries/cry_dewpider.bin"

	.align 2
Cry_Dhelmise::
	.incbin "sound/direct_sound_samples/cries/cry_dhelmise.bin"

	.align 2
Cry_Dialga::
	.incbin "sound/direct_sound_samples/cries/cry_dialga.bin"

	.align 2
Cry_Diancie::
	.incbin "sound/direct_sound_samples/cries/cry_diancie.bin"

	.align 2
Cry_Diggersby::
	.incbin "sound/direct_sound_samples/cries/cry_diggersby.bin"

	.align 2
Cry_Doublade::
	.incbin "sound/direct_sound_samples/cries/cry_doublade.bin"

	.align 2
Cry_Dragalge::
	.incbin "sound/direct_sound_samples/cries/cry_dragalge.bin"

	.align 2
Cry_Drampa::
	.incbin "sound/direct_sound_samples/cries/cry_drampa.bin"

	.align 2
Cry_Drapion::
	.incbin "sound/direct_sound_samples/cries/cry_drapion.bin"

	.align 2
Cry_Drifblim::
	.incbin "sound/direct_sound_samples/cries/cry_drifblim.bin"

	.align 2
Cry_Drifloon::
	.incbin "sound/direct_sound_samples/cries/cry_drifloon.bin"

	.align 2
Cry_Drilbur::
	.incbin "sound/direct_sound_samples/cries/cry_drilbur.bin"

	.align 2
Cry_Druddigon::
	.incbin "sound/direct_sound_samples/cries/cry_druddigon.bin"

	.align 2
Cry_Ducklett::
	.incbin "sound/direct_sound_samples/cries/cry_ducklett.bin"

	.align 2
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cries/cry_duosion.bin"

	.align 2
Cry_Durant::
	.incbin "sound/direct_sound_samples/cries/cry_durant.bin"

	.align 2
Cry_Dusknoir::
	.incbin "sound/direct_sound_samples/cries/cry_dusknoir.bin"

	.align 2
Cry_Dwebble::
	.incbin "sound/direct_sound_samples/cries/cry_dwebble.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cries/cry_eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cries/cry_eelektross.bin"

	.align 2
Cry_Electivire::
	.incbin "sound/direct_sound_samples/cries/cry_electivire.bin"

	.align 2
Cry_Elgyem::
	.incbin "sound/direct_sound_samples/cries/cry_elgyem.bin"

	.align 2
Cry_Emboar::
	.incbin "sound/direct_sound_samples/cries/cry_emboar.bin"

	.align 2
Cry_Emolga::
	.incbin "sound/direct_sound_samples/cries/cry_emolga.bin"

	.align 2
Cry_Empoleon::
	.incbin "sound/direct_sound_samples/cries/cry_empoleon.bin"

	.align 2
Cry_Escavalier::
	.incbin "sound/direct_sound_samples/cries/cry_escavalier.bin"

	.align 2
Cry_Espurr::
	.incbin "sound/direct_sound_samples/cries/cry_espurr.bin"

	.align 2
Cry_Excadrill::
	.incbin "sound/direct_sound_samples/cries/cry_excadrill.bin"

	.align 2
Cry_Fennekin::
	.incbin "sound/direct_sound_samples/cries/cry_fennekin.bin"

	.align 2
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cries/cry_ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cries/cry_ferrothorn.bin"

	.align 2
Cry_Finneon::
	.incbin "sound/direct_sound_samples/cries/cry_finneon.bin"

	.align 2
Cry_Flabebe::
	.incbin "sound/direct_sound_samples/cries/cry_flabebe.bin"

	.align 2
Cry_Fletchinder::
	.incbin "sound/direct_sound_samples/cries/cry_fletchinder.bin"

	.align 2
Cry_Fletchling::
	.incbin "sound/direct_sound_samples/cries/cry_fletchling.bin"

	.align 2
Cry_Floatzel::
	.incbin "sound/direct_sound_samples/cries/cry_floatzel.bin"

	.align 2
Cry_Floette::
	.incbin "sound/direct_sound_samples/cries/cry_floette.bin"

	.align 2
Cry_Florges::
	.incbin "sound/direct_sound_samples/cries/cry_florges.bin"

	.align 2
Cry_Fomantis::
	.incbin "sound/direct_sound_samples/cries/cry_fomantis.bin"

	.align 2
Cry_Foongus::
	.incbin "sound/direct_sound_samples/cries/cry_foongus.bin"

	.align 2
Cry_Fraxure::
	.incbin "sound/direct_sound_samples/cries/cry_fraxure.bin"

	.align 2
Cry_Frillish::
	.incbin "sound/direct_sound_samples/cries/cry_frillish.bin"

	.align 2
Cry_Froakie::
	.incbin "sound/direct_sound_samples/cries/cry_froakie.bin"

	.align 2
Cry_Frogadier::
	.incbin "sound/direct_sound_samples/cries/cry_frogadier.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cries/cry_froslass.bin"

	.align 2
Cry_Furfrou::
	.incbin "sound/direct_sound_samples/cries/cry_furfrou.bin"

	.align 2
Cry_Gabite::
	.incbin "sound/direct_sound_samples/cries/cry_gabite.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cries/cry_gallade.bin"

	.align 2
Cry_Galvantula::
	.incbin "sound/direct_sound_samples/cries/cry_galvantula.bin"

	.align 2
Cry_Garbodor::
	.incbin "sound/direct_sound_samples/cries/cry_garbodor.bin"

	.align 2
Cry_Garchomp::
	.incbin "sound/direct_sound_samples/cries/cry_garchomp.bin"

	.align 2
Cry_Gastrodon::
	.incbin "sound/direct_sound_samples/cries/cry_gastrodon.bin"

	.align 2
Cry_Genesect::
	.incbin "sound/direct_sound_samples/cries/cry_genesect.bin"

	.align 2
Cry_Gible::
	.incbin "sound/direct_sound_samples/cries/cry_gible.bin"

	.align 2
Cry_Gigalith::
	.incbin "sound/direct_sound_samples/cries/cry_gigalith.bin"

	.align 2
Cry_Giratina::
	.incbin "sound/direct_sound_samples/cries/cry_giratina.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/cry_glaceon.bin"

	.align 2
Cry_Glameow::
	.incbin "sound/direct_sound_samples/cries/cry_glameow.bin"

	.align 2
Cry_Gliscor::
	.incbin "sound/direct_sound_samples/cries/cry_gliscor.bin"

	.align 2
Cry_Gogoat::
	.incbin "sound/direct_sound_samples/cries/cry_gogoat.bin"

	.align 2
Cry_Golett::
	.incbin "sound/direct_sound_samples/cries/cry_golett.bin"

	.align 2
Cry_Golisopod::
	.incbin "sound/direct_sound_samples/cries/cry_golisopod.bin"

	.align 2
Cry_Golurk::
	.incbin "sound/direct_sound_samples/cries/cry_golurk.bin"

	.align 2
Cry_Goodra::
	.incbin "sound/direct_sound_samples/cries/cry_goodra.bin"

	.align 2
Cry_Goomy::
	.incbin "sound/direct_sound_samples/cries/cry_goomy.bin"

	.align 2
Cry_Gothita::
	.incbin "sound/direct_sound_samples/cries/cry_gothita.bin"

	.align 2
Cry_Gothitelle::
	.incbin "sound/direct_sound_samples/cries/cry_gothitelle.bin"

	.align 2
Cry_Gothorita::
	.incbin "sound/direct_sound_samples/cries/cry_gothorita.bin"

	.align 2
Cry_Gourgeist::
	.incbin "sound/direct_sound_samples/cries/cry_gourgeist.bin"

	.align 2
Cry_Greninja::
	.incbin "sound/direct_sound_samples/cries/cry_greninja.bin"

	.align 2
Cry_Grotle::
	.incbin "sound/direct_sound_samples/cries/cry_grotle.bin"

	.align 2
Cry_Grubbin::
	.incbin "sound/direct_sound_samples/cries/cry_grubbin.bin"

	.align 2
Cry_Gumshoos::
	.incbin "sound/direct_sound_samples/cries/cry_gumshoos.bin"

	.align 2
Cry_Gurdurr::
	.incbin "sound/direct_sound_samples/cries/cry_gurdurr.bin"

	.align 2
Cry_Guzzlord::
	.incbin "sound/direct_sound_samples/cries/cry_guzzlord.bin"

	.align 2
Cry_HakamoO::
	.incbin "sound/direct_sound_samples/cries/cry_hakamo-o.bin"

	.align 2
Cry_Happiny::
	.incbin "sound/direct_sound_samples/cries/cry_happiny.bin"

	.align 2
Cry_Hawlucha::
	.incbin "sound/direct_sound_samples/cries/cry_hawlucha.bin"

	.align 2
Cry_Haxorus::
	.incbin "sound/direct_sound_samples/cries/cry_haxorus.bin"

	.align 2
Cry_Heatmor::
	.incbin "sound/direct_sound_samples/cries/cry_heatmor.bin"

	.align 2
Cry_Heatran::
	.incbin "sound/direct_sound_samples/cries/cry_heatran.bin"

	.align 2
Cry_Heliolisk::
	.incbin "sound/direct_sound_samples/cries/cry_heliolisk.bin"

	.align 2
Cry_Helioptile::
	.incbin "sound/direct_sound_samples/cries/cry_helioptile.bin"

	.align 2
Cry_Herdier::
	.incbin "sound/direct_sound_samples/cries/cry_herdier.bin"

	.align 2
Cry_Hippopotas::
	.incbin "sound/direct_sound_samples/cries/cry_hippopotas.bin"

	.align 2
Cry_Hippowdon::
	.incbin "sound/direct_sound_samples/cries/cry_hippowdon.bin"

	.align 2
Cry_Honchkrow::
	.incbin "sound/direct_sound_samples/cries/cry_honchkrow.bin"

	.align 2
Cry_Honedge::
	.incbin "sound/direct_sound_samples/cries/cry_honedge.bin"

	.align 2
Cry_Hoopa::
	.incbin "sound/direct_sound_samples/cries/cry_hoopa.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cries/cry_hydreigon.bin"

	.align 2
Cry_Incineroar::
	.incbin "sound/direct_sound_samples/cries/cry_incineroar.bin"

	.align 2
Cry_Infernape::
	.incbin "sound/direct_sound_samples/cries/cry_infernape.bin"

	.align 2
Cry_Inkay::
	.incbin "sound/direct_sound_samples/cries/cry_inkay.bin"

	.align 2
Cry_JangmoO::
	.incbin "sound/direct_sound_samples/cries/cry_jangmo-o.bin"

	.align 2
Cry_Jellicent::
	.incbin "sound/direct_sound_samples/cries/cry_jellicent.bin"

	.align 2
Cry_Joltik::
	.incbin "sound/direct_sound_samples/cries/cry_joltik.bin"

	.align 2
Cry_Karrablast::
	.incbin "sound/direct_sound_samples/cries/cry_karrablast.bin"

	.align 2
Cry_Kartana::
	.incbin "sound/direct_sound_samples/cries/cry_kartana.bin"

	.align 2
Cry_Keldeo::
	.incbin "sound/direct_sound_samples/cries/cry_keldeo.bin"

	.align 2
Cry_Klang::
	.incbin "sound/direct_sound_samples/cries/cry_klang.bin"

	.align 2
Cry_Klefki::
	.incbin "sound/direct_sound_samples/cries/cry_klefki.bin"

	.align 2
Cry_Klink::
	.incbin "sound/direct_sound_samples/cries/cry_klink.bin"

	.align 2
Cry_Klinklang::
	.incbin "sound/direct_sound_samples/cries/cry_klinklang.bin"

	.align 2
Cry_Komala::
	.incbin "sound/direct_sound_samples/cries/cry_komala.bin"

	.align 2
Cry_KommoO::
	.incbin "sound/direct_sound_samples/cries/cry_kommo-o.bin"

	.align 2
Cry_Kricketot::
	.incbin "sound/direct_sound_samples/cries/cry_kricketot.bin"

	.align 2
Cry_Kricketune::
	.incbin "sound/direct_sound_samples/cries/cry_kricketune.bin"

	.align 2
Cry_Krokorok::
	.incbin "sound/direct_sound_samples/cries/cry_krokorok.bin"

	.align 2
Cry_Krookodile::
	.incbin "sound/direct_sound_samples/cries/cry_krookodile.bin"

	.align 2
Cry_Kyurem::
	.incbin "sound/direct_sound_samples/cries/cry_kyurem.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cries/cry_lampent.bin"

	.align 2
Cry_Landorus::
	.incbin "sound/direct_sound_samples/cries/cry_landorus.bin"

	.align 2
Cry_Larvesta::
	.incbin "sound/direct_sound_samples/cries/cry_larvesta.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/cry_leafeon.bin"

	.align 2
Cry_Leavanny::
	.incbin "sound/direct_sound_samples/cries/cry_leavanny.bin"

	.align 2
Cry_Lickilicky::
	.incbin "sound/direct_sound_samples/cries/cry_lickilicky.bin"

	.align 2
Cry_Liepard::
	.incbin "sound/direct_sound_samples/cries/cry_liepard.bin"

	.align 2
Cry_Lilligant::
	.incbin "sound/direct_sound_samples/cries/cry_lilligant.bin"

	.align 2
Cry_Lillipup::
	.incbin "sound/direct_sound_samples/cries/cry_lillipup.bin"

	.align 2
Cry_Litleo::
	.incbin "sound/direct_sound_samples/cries/cry_litleo.bin"

	.align 2
Cry_Litten::
	.incbin "sound/direct_sound_samples/cries/cry_litten.bin"

	.align 2
Cry_Litwick::
	.incbin "sound/direct_sound_samples/cries/cry_litwick.bin"

	.align 2
Cry_Lopunny::
	.incbin "sound/direct_sound_samples/cries/cry_lopunny.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cries/cry_lucario.bin"

	.align 2
Cry_Lumineon::
	.incbin "sound/direct_sound_samples/cries/cry_lumineon.bin"

	.align 2
Cry_Lunala::
	.incbin "sound/direct_sound_samples/cries/cry_lunala.bin"

	.align 2
Cry_Lurantis::
	.incbin "sound/direct_sound_samples/cries/cry_lurantis.bin"

	.align 2
Cry_Luxio::
	.incbin "sound/direct_sound_samples/cries/cry_luxio.bin"

	.align 2
Cry_Luxray::
	.incbin "sound/direct_sound_samples/cries/cry_luxray.bin"

	.align 2
Cry_Lycanroc::
	.incbin "sound/direct_sound_samples/cries/cry_lycanroc.bin"

	.align 2
Cry_Magearna::
	.incbin "sound/direct_sound_samples/cries/cry_magearna.bin"

	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cries/cry_magmortar.bin"

	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cries/cry_magnezone.bin"

	.align 2
Cry_Malamar::
	.incbin "sound/direct_sound_samples/cries/cry_malamar.bin"

	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cries/cry_mamoswine.bin"

	.align 2
Cry_Manaphy::
	.incbin "sound/direct_sound_samples/cries/cry_manaphy.bin"

	.align 2
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cries/cry_mandibuzz.bin"

	.align 2
Cry_Mantyke::
	.incbin "sound/direct_sound_samples/cries/cry_mantyke.bin"

	.align 2
Cry_Maractus::
	.incbin "sound/direct_sound_samples/cries/cry_maractus.bin"

	.align 2
Cry_Mareanie::
	.incbin "sound/direct_sound_samples/cries/cry_mareanie.bin"

	.align 2
Cry_Marshadow::
	.incbin "sound/direct_sound_samples/cries/cry_marshadow.bin"

	.align 2
Cry_Melmetal::
	.incbin "sound/direct_sound_samples/cries/cry_melmetal.bin"

	.align 2
Cry_Meloetta::
	.incbin "sound/direct_sound_samples/cries/cry_meloetta.bin"

	.align 2
Cry_Meltan::
	.incbin "sound/direct_sound_samples/cries/cry_meltan.bin"

	.align 2
Cry_Meowstic::
	.incbin "sound/direct_sound_samples/cries/cry_meowstic.bin"

	.align 2
Cry_Mesprit::
	.incbin "sound/direct_sound_samples/cries/cry_mesprit.bin"

	.align 2
Cry_Mienfoo::
	.incbin "sound/direct_sound_samples/cries/cry_mienfoo.bin"

	.align 2
Cry_Mienshao::
	.incbin "sound/direct_sound_samples/cries/cry_mienshao.bin"

	.align 2
Cry_Mime_Jr::
	.incbin "sound/direct_sound_samples/cries/cry_mime_jr.bin"

	.align 2
Cry_Mimikyu::
	.incbin "sound/direct_sound_samples/cries/cry_mimikyu.bin"

	.align 2
Cry_Minccino::
	.incbin "sound/direct_sound_samples/cries/cry_minccino.bin"

	.align 2
Cry_Minior::
	.incbin "sound/direct_sound_samples/cries/cry_minior.bin"

	.align 2
Cry_Mismagius::
	.incbin "sound/direct_sound_samples/cries/cry_mismagius.bin"

	.align 2
Cry_Monferno::
	.incbin "sound/direct_sound_samples/cries/cry_monferno.bin"

	.align 2
Cry_Morelull::
	.incbin "sound/direct_sound_samples/cries/cry_morelull.bin"

	.align 2
Cry_Mothim::
	.incbin "sound/direct_sound_samples/cries/cry_mothim.bin"

	.align 2
Cry_Mudbray::
	.incbin "sound/direct_sound_samples/cries/cry_mudbray.bin"

	.align 2
Cry_Mudsdale::
	.incbin "sound/direct_sound_samples/cries/cry_mudsdale.bin"

	.align 2
Cry_Munchlax::
	.incbin "sound/direct_sound_samples/cries/cry_munchlax.bin"

	.align 2
Cry_Munna::
	.incbin "sound/direct_sound_samples/cries/cry_munna.bin"

	.align 2
Cry_Musharna::
	.incbin "sound/direct_sound_samples/cries/cry_musharna.bin"

	.align 2
Cry_Naganadel::
	.incbin "sound/direct_sound_samples/cries/cry_naganadel.bin"

	.align 2
Cry_Necrozma::
	.incbin "sound/direct_sound_samples/cries/cry_necrozma.bin"

	.align 2
Cry_Nihilego::
	.incbin "sound/direct_sound_samples/cries/cry_nihilego.bin"

	.align 2
Cry_Noibat::
	.incbin "sound/direct_sound_samples/cries/cry_noibat.bin"

	.align 2
Cry_Noivern::
	.incbin "sound/direct_sound_samples/cries/cry_noivern.bin"

	.align 2
Cry_Oranguru::
	.incbin "sound/direct_sound_samples/cries/cry_oranguru.bin"

	.align 2
Cry_Oricorio::
	.incbin "sound/direct_sound_samples/cries/cry_oricorio.bin"

	.align 2
Cry_Oshawott::
	.incbin "sound/direct_sound_samples/cries/cry_oshawott.bin"

	.align 2
Cry_Pachirisu::
	.incbin "sound/direct_sound_samples/cries/cry_pachirisu.bin"

	.align 2
Cry_Palkia::
	.incbin "sound/direct_sound_samples/cries/cry_palkia.bin"

	.align 2
Cry_Palossand::
	.incbin "sound/direct_sound_samples/cries/cry_palossand.bin"

	.align 2
Cry_Palpitoad::
	.incbin "sound/direct_sound_samples/cries/cry_palpitoad.bin"

	.align 2
Cry_Pancham::
	.incbin "sound/direct_sound_samples/cries/cry_pancham.bin"

	.align 2
Cry_Pangoro::
	.incbin "sound/direct_sound_samples/cries/cry_pangoro.bin"

	.align 2
Cry_Panpour::
	.incbin "sound/direct_sound_samples/cries/cry_panpour.bin"

	.align 2
Cry_Pansage::
	.incbin "sound/direct_sound_samples/cries/cry_pansage.bin"

	.align 2
Cry_Pansear::
	.incbin "sound/direct_sound_samples/cries/cry_pansear.bin"

	.align 2
Cry_Passimian::
	.incbin "sound/direct_sound_samples/cries/cry_passimian.bin"

	.align 2
Cry_Patrat::
	.incbin "sound/direct_sound_samples/cries/cry_patrat.bin"

	.align 2
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cries/cry_pawniard.bin"

	.align 2
Cry_Petilil::
	.incbin "sound/direct_sound_samples/cries/cry_petilil.bin"

	.align 2
Cry_Phantump::
	.incbin "sound/direct_sound_samples/cries/cry_phantump.bin"

	.align 2
Cry_Pheromosa::
	.incbin "sound/direct_sound_samples/cries/cry_pheromosa.bin"

	.align 2
Cry_Phione::
	.incbin "sound/direct_sound_samples/cries/cry_phione.bin"

	.align 2
Cry_Pidove::
	.incbin "sound/direct_sound_samples/cries/cry_pidove.bin"

	.align 2
Cry_Pignite::
	.incbin "sound/direct_sound_samples/cries/cry_pignite.bin"

	.align 2
Cry_Pikipek::
	.incbin "sound/direct_sound_samples/cries/cry_pikipek.bin"

	.align 2
Cry_Piplup::
	.incbin "sound/direct_sound_samples/cries/cry_piplup.bin"

	.align 2
Cry_Poipole::
	.incbin "sound/direct_sound_samples/cries/cry_poipole.bin"

	.align 2
Cry_Popplio::
	.incbin "sound/direct_sound_samples/cries/cry_popplio.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/cry_porygon-z.bin"

	.align 2
Cry_Primarina::
	.incbin "sound/direct_sound_samples/cries/cry_primarina.bin"

	.align 2
Cry_Prinplup::
	.incbin "sound/direct_sound_samples/cries/cry_prinplup.bin"

	.align 2
Cry_Probopass::
	.incbin "sound/direct_sound_samples/cries/cry_probopass.bin"

	.align 2
Cry_Pumpkaboo::
	.incbin "sound/direct_sound_samples/cries/cry_pumpkaboo.bin"

	.align 2
Cry_Purrloin::
	.incbin "sound/direct_sound_samples/cries/cry_purrloin.bin"

	.align 2
Cry_Purugly::
	.incbin "sound/direct_sound_samples/cries/cry_purugly.bin"

	.align 2
Cry_Pyroar::
	.incbin "sound/direct_sound_samples/cries/cry_pyroar.bin"

	.align 2
Cry_Pyukumuku::
	.incbin "sound/direct_sound_samples/cries/cry_pyukumuku.bin"

	.align 2
Cry_Quilladin::
	.incbin "sound/direct_sound_samples/cries/cry_quilladin.bin"

	.align 2
Cry_Rampardos::
	.incbin "sound/direct_sound_samples/cries/cry_rampardos.bin"

	.align 2
Cry_Regigigas::
	.incbin "sound/direct_sound_samples/cries/cry_regigigas.bin"

	.align 2
Cry_Reshiram::
	.incbin "sound/direct_sound_samples/cries/cry_reshiram.bin"

	.align 2
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cries/cry_reuniclus.bin"

	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cries/cry_rhyperior.bin"

	.align 2
Cry_Ribombee::
	.incbin "sound/direct_sound_samples/cries/cry_ribombee.bin"

	.align 2
Cry_Riolu::
	.incbin "sound/direct_sound_samples/cries/cry_riolu.bin"

	.align 2
Cry_Rockruff::
	.incbin "sound/direct_sound_samples/cries/cry_rockruff.bin"

	.align 2
Cry_Roggenrola::
	.incbin "sound/direct_sound_samples/cries/cry_roggenrola.bin"

	.align 2
Cry_Roserade::
	.incbin "sound/direct_sound_samples/cries/cry_roserade.bin"

	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cries/cry_rotom.bin"

	.align 2
Cry_Rowlet::
	.incbin "sound/direct_sound_samples/cries/cry_rowlet.bin"

	.align 2
Cry_Rufflet::
	.incbin "sound/direct_sound_samples/cries/cry_rufflet.bin"

	.align 2
Cry_Salandit::
	.incbin "sound/direct_sound_samples/cries/cry_salandit.bin"

	.align 2
Cry_Salazzle::
	.incbin "sound/direct_sound_samples/cries/cry_salazzle.bin"

	.align 2
Cry_Samurott::
	.incbin "sound/direct_sound_samples/cries/cry_samurott.bin"

	.align 2
Cry_Sandile::
	.incbin "sound/direct_sound_samples/cries/cry_sandile.bin"

	.align 2
Cry_Sandygast::
	.incbin "sound/direct_sound_samples/cries/cry_sandygast.bin"

	.align 2
Cry_Sawk::
	.incbin "sound/direct_sound_samples/cries/cry_sawk.bin"

	.align 2
Cry_Sawsbuck::
	.incbin "sound/direct_sound_samples/cries/cry_sawsbuck.bin"

	.align 2
Cry_Scatterbug::
	.incbin "sound/direct_sound_samples/cries/cry_scatterbug.bin"

	.align 2
Cry_Scolipede::
	.incbin "sound/direct_sound_samples/cries/cry_scolipede.bin"

	.align 2
Cry_Scrafty::
	.incbin "sound/direct_sound_samples/cries/cry_scrafty.bin"

	.align 2
Cry_Scraggy::
	.incbin "sound/direct_sound_samples/cries/cry_scraggy.bin"

	.align 2
Cry_Seismitoad::
	.incbin "sound/direct_sound_samples/cries/cry_seismitoad.bin"

	.align 2
Cry_Serperior::
	.incbin "sound/direct_sound_samples/cries/cry_serperior.bin"

	.align 2
Cry_Servine::
	.incbin "sound/direct_sound_samples/cries/cry_servine.bin"

	.align 2
Cry_Sewaddle::
	.incbin "sound/direct_sound_samples/cries/cry_sewaddle.bin"

	.align 2
Cry_Shaymin::
	.incbin "sound/direct_sound_samples/cries/cry_shaymin.bin"

	.align 2
Cry_Shellos::
	.incbin "sound/direct_sound_samples/cries/cry_shellos.bin"

	.align 2
Cry_Shelmet::
	.incbin "sound/direct_sound_samples/cries/cry_shelmet.bin"

	.align 2
Cry_Shieldon::
	.incbin "sound/direct_sound_samples/cries/cry_shieldon.bin"

	.align 2
Cry_Shiinotic::
	.incbin "sound/direct_sound_samples/cries/cry_shiinotic.bin"

	.align 2
Cry_Shinx::
	.incbin "sound/direct_sound_samples/cries/cry_shinx.bin"

	.align 2
Cry_Sigilyph::
	.incbin "sound/direct_sound_samples/cries/cry_sigilyph.bin"

	.align 2
Cry_Silvally::
	.incbin "sound/direct_sound_samples/cries/cry_silvally.bin"

	.align 2
Cry_Simipour::
	.incbin "sound/direct_sound_samples/cries/cry_simipour.bin"

	.align 2
Cry_Simisage::
	.incbin "sound/direct_sound_samples/cries/cry_simisage.bin"

	.align 2
Cry_Simisear::
	.incbin "sound/direct_sound_samples/cries/cry_simisear.bin"

	.align 2
Cry_Skiddo::
	.incbin "sound/direct_sound_samples/cries/cry_skiddo.bin"

	.align 2
Cry_Skorupi::
	.incbin "sound/direct_sound_samples/cries/cry_skorupi.bin"

	.align 2
Cry_Skrelp::
	.incbin "sound/direct_sound_samples/cries/cry_skrelp.bin"

	.align 2
Cry_Skuntank::
	.incbin "sound/direct_sound_samples/cries/cry_skuntank.bin"

	.align 2
Cry_Sliggoo::
	.incbin "sound/direct_sound_samples/cries/cry_sliggoo.bin"

	.align 2
Cry_Slurpuff::
	.incbin "sound/direct_sound_samples/cries/cry_slurpuff.bin"

	.align 2
Cry_Snivy::
	.incbin "sound/direct_sound_samples/cries/cry_snivy.bin"

	.align 2
Cry_Snover::
	.incbin "sound/direct_sound_samples/cries/cry_snover.bin"

	.align 2
Cry_Solgaleo::
	.incbin "sound/direct_sound_samples/cries/cry_solgaleo.bin"

	.align 2
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cries/cry_solosis.bin"

	.align 2
Cry_Spewpa::
	.incbin "sound/direct_sound_samples/cries/cry_spewpa.bin"

	.align 2
Cry_Spiritomb::
	.incbin "sound/direct_sound_samples/cries/cry_spiritomb.bin"

	.align 2
Cry_Spritzee::
	.incbin "sound/direct_sound_samples/cries/cry_spritzee.bin"

	.align 2
Cry_Stakataka::
	.incbin "sound/direct_sound_samples/cries/cry_stakataka.bin"

	.align 2
Cry_Staraptor::
	.incbin "sound/direct_sound_samples/cries/cry_staraptor.bin"

	.align 2
Cry_Staravia::
	.incbin "sound/direct_sound_samples/cries/cry_staravia.bin"

	.align 2
Cry_Starly::
	.incbin "sound/direct_sound_samples/cries/cry_starly.bin"

	.align 2
Cry_Steenee::
	.incbin "sound/direct_sound_samples/cries/cry_steenee.bin"

	.align 2
Cry_Stoutland::
	.incbin "sound/direct_sound_samples/cries/cry_stoutland.bin"

	.align 2
Cry_Stufful::
	.incbin "sound/direct_sound_samples/cries/cry_stufful.bin"

	.align 2
Cry_Stunfisk::
	.incbin "sound/direct_sound_samples/cries/cry_stunfisk.bin"

	.align 2
Cry_Stunky::
	.incbin "sound/direct_sound_samples/cries/cry_stunky.bin"

	.align 2
Cry_Swadloon::
	.incbin "sound/direct_sound_samples/cries/cry_swadloon.bin"

	.align 2
Cry_Swanna::
	.incbin "sound/direct_sound_samples/cries/cry_swanna.bin"

	.align 2
Cry_Swirlix::
	.incbin "sound/direct_sound_samples/cries/cry_swirlix.bin"

	.align 2
Cry_Swoobat::
	.incbin "sound/direct_sound_samples/cries/cry_swoobat.bin"

	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cries/cry_sylveon.bin"

	.align 2
Cry_Talonflame::
	.incbin "sound/direct_sound_samples/cries/cry_talonflame.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cries/cry_tangrowth.bin"

	.align 2
Cry_Tapu_Bulu::
	.incbin "sound/direct_sound_samples/cries/cry_tapu_bulu.bin"

	.align 2
Cry_Tapu_Fini::
	.incbin "sound/direct_sound_samples/cries/cry_tapu_fini.bin"

	.align 2
Cry_Tapu_Koko::
	.incbin "sound/direct_sound_samples/cries/cry_tapu_koko.bin"

	.align 2
Cry_Tapu_Lele::
	.incbin "sound/direct_sound_samples/cries/cry_tapu_lele.bin"

	.align 2
Cry_Tepig::
	.incbin "sound/direct_sound_samples/cries/cry_tepig.bin"

	.align 2
Cry_Terrakion::
	.incbin "sound/direct_sound_samples/cries/cry_terrakion.bin"

	.align 2
Cry_Throh::
	.incbin "sound/direct_sound_samples/cries/cry_throh.bin"

	.align 2
Cry_Thundurus::
	.incbin "sound/direct_sound_samples/cries/cry_thundurus.bin"

	.align 2
Cry_Timburr::
	.incbin "sound/direct_sound_samples/cries/cry_timburr.bin"

	.align 2
Cry_Tirtouga::
	.incbin "sound/direct_sound_samples/cries/cry_tirtouga.bin"

	.align 2
Cry_Togedemaru::
	.incbin "sound/direct_sound_samples/cries/cry_togedemaru.bin"

	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cries/cry_togekiss.bin"

	.align 2
Cry_Tornadus::
	.incbin "sound/direct_sound_samples/cries/cry_tornadus.bin"

	.align 2
Cry_Torracat::
	.incbin "sound/direct_sound_samples/cries/cry_torracat.bin"

	.align 2
Cry_Torterra::
	.incbin "sound/direct_sound_samples/cries/cry_torterra.bin"

	.align 2
Cry_Toucannon::
	.incbin "sound/direct_sound_samples/cries/cry_toucannon.bin"

	.align 2
Cry_Toxapex::
	.incbin "sound/direct_sound_samples/cries/cry_toxapex.bin"

	.align 2
Cry_Toxicroak::
	.incbin "sound/direct_sound_samples/cries/cry_toxicroak.bin"

	.align 2
Cry_Tranquill::
	.incbin "sound/direct_sound_samples/cries/cry_tranquill.bin"

	.align 2
Cry_Trevenant::
	.incbin "sound/direct_sound_samples/cries/cry_trevenant.bin"

	.align 2
Cry_Trubbish::
	.incbin "sound/direct_sound_samples/cries/cry_trubbish.bin"

	.align 2
Cry_Trumbeak::
	.incbin "sound/direct_sound_samples/cries/cry_trumbeak.bin"

	.align 2
Cry_Tsareena::
	.incbin "sound/direct_sound_samples/cries/cry_tsareena.bin"

	.align 2
Cry_Turtonator::
	.incbin "sound/direct_sound_samples/cries/cry_turtonator.bin"

	.align 2
Cry_Turtwig::
	.incbin "sound/direct_sound_samples/cries/cry_turtwig.bin"

	.align 2
Cry_Tympole::
	.incbin "sound/direct_sound_samples/cries/cry_tympole.bin"

	.align 2
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cries/cry_tynamo.bin"

	.align 2
Cry_Type_Null::
	.incbin "sound/direct_sound_samples/cries/cry_type_null.bin"

	.align 2
Cry_Tyrantrum::
	.incbin "sound/direct_sound_samples/cries/cry_tyrantrum.bin"

	.align 2
Cry_Tyrunt::
	.incbin "sound/direct_sound_samples/cries/cry_tyrunt.bin"

	.align 2
Cry_Unfezant::
	.incbin "sound/direct_sound_samples/cries/cry_unfezant.bin"

	.align 2
Cry_Uxie::
	.incbin "sound/direct_sound_samples/cries/cry_uxie.bin"

	.align 2
Cry_Vanillish::
	.incbin "sound/direct_sound_samples/cries/cry_vanillish.bin"

	.align 2
Cry_Vanillite::
	.incbin "sound/direct_sound_samples/cries/cry_vanillite.bin"

	.align 2
Cry_Vanilluxe::
	.incbin "sound/direct_sound_samples/cries/cry_vanilluxe.bin"

	.align 2
Cry_Venipede::
	.incbin "sound/direct_sound_samples/cries/cry_venipede.bin"

	.align 2
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cries/cry_vespiquen.bin"

	.align 2
Cry_Victini::
	.incbin "sound/direct_sound_samples/cries/cry_victini.bin"

	.align 2
Cry_Vikavolt::
	.incbin "sound/direct_sound_samples/cries/cry_vikavolt.bin"

	.align 2
Cry_Virizion::
	.incbin "sound/direct_sound_samples/cries/cry_virizion.bin"

	.align 2
Cry_Vivillon::
	.incbin "sound/direct_sound_samples/cries/cry_vivillon.bin"

	.align 2
Cry_Volcanion::
	.incbin "sound/direct_sound_samples/cries/cry_volcanion.bin"

	.align 2
Cry_Volcarona::
	.incbin "sound/direct_sound_samples/cries/cry_volcarona.bin"

	.align 2
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cries/cry_vullaby.bin"

	.align 2
Cry_Watchog::
	.incbin "sound/direct_sound_samples/cries/cry_watchog.bin"

	.align 2
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cries/cry_weavile.bin"

	.align 2
Cry_Whimsicott::
	.incbin "sound/direct_sound_samples/cries/cry_whimsicott.bin"

	.align 2
Cry_Whirlipede::
	.incbin "sound/direct_sound_samples/cries/cry_whirlipede.bin"

	.align 2
Cry_Wimpod::
	.incbin "sound/direct_sound_samples/cries/cry_wimpod.bin"

	.align 2
Cry_Wishiwashi::
	.incbin "sound/direct_sound_samples/cries/cry_wishiwashi.bin"

	.align 2
Cry_Woobat::
	.incbin "sound/direct_sound_samples/cries/cry_woobat.bin"

	.align 2
Cry_Wormadam::
	.incbin "sound/direct_sound_samples/cries/cry_wormadam.bin"

	.align 2
Cry_Xerneas::
	.incbin "sound/direct_sound_samples/cries/cry_xerneas.bin"

	.align 2
Cry_Xurkitree::
	.incbin "sound/direct_sound_samples/cries/cry_xurkitree.bin"

	.align 2
Cry_Yamask::
	.incbin "sound/direct_sound_samples/cries/cry_yamask.bin"

	.align 2
Cry_Yanmega::
	.incbin "sound/direct_sound_samples/cries/cry_yanmega.bin"

	.align 2
Cry_Yungoos::
	.incbin "sound/direct_sound_samples/cries/cry_yungoos.bin"

	.align 2
Cry_Yveltal::
	.incbin "sound/direct_sound_samples/cries/cry_yveltal.bin"

	.align 2
Cry_Zebstrika::
	.incbin "sound/direct_sound_samples/cries/cry_zebstrika.bin"

	.align 2
Cry_Zekrom::
	.incbin "sound/direct_sound_samples/cries/cry_zekrom.bin"

	.align 2
Cry_Zeraora::
	.incbin "sound/direct_sound_samples/cries/cry_zeraora.bin"

	.align 2
Cry_Zoroark::
	.incbin "sound/direct_sound_samples/cries/cry_zoroark.bin"

	.align 2
Cry_Zorua::
	.incbin "sound/direct_sound_samples/cries/cry_zorua.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cries/cry_zweilous.bin"

	.align 2
Cry_Zygarde::
	.incbin "sound/direct_sound_samples/cries/cry_zygarde.bin"
